### PR TITLE
fix: pass core to fetch function

### LINKED ISSUE #617: clone does not use credentialManager from the specified core
The clone function does not pass the specified core to the fetch function (and in turn discover, then fetchPackfile). As a result, it does not end up using the credentialManager in the specified core.

Even though the core is not always needed, it should be passed to delegate functions in case it needs to be consulted by one of those functions. However, this seems to be the only case where the core is consulted in a place other than the arguments list.

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #617

## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by mojavelinux** [comment]
I noticed the credentialManager doesn't have any tests. Perhaps we should add some tests, then also very that it gets used by clone when set on an alternate plugin core?

**Comment by karma-pr-reporter** [comment]
## Test Results for 6aa6920ed88db53c2c862b4a7d87c47e1cfc14dd:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 224 | 1 | 0 | 57.303 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 224 | 1 | 0 | 1 min 32.612 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 224 | 1 | 0 | 2 mins 55.17 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 3 mins 21.629 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 224 | 1 | 0 | 3 mins 43.468 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 224 | 1 | 0 | 4 mins 36.291 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for a51f19fb477bcc9ff1b29130b356b3665dba2135:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 224 | 1 | 0 | 57.076 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 224 | 1 | 0 | 1 min 33.716 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 224 | 1 | 0 | 3 mins 2.949 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 3 mins 9.351 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 224 | 1 | 0 | 3 mins 35.089 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 224 | 1 | 0 | 4 mins 9.443 secs | false | undefined |

**Comment by wmhilton** [comment]
> I noticed the credentialManager doesn't have any tests. Perhaps we should add some tests, then also very that it gets used by clone when set on an alternate plugin core?

The credentialManager is just an interface, so I'm not sure how you would test it. I guess you're thinking of making a mock/spy credentialManager and making sure it gets called? I suppose so... sadly Jest's sweet mocking library isn't available in the browser so we'd have to figure out how to do it in pure Jasmine.

**Pull request merged**
