### PR TITLE
Harmonize the semicolons in code examples

### PR DESCRIPTION
**Pull request by TomasHubelbauer**
Some lines had them, some didn't, now none do because there was more of the ones that didn't and this is a democracy.

## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for e0fea1e5eadb7af28da9b5a167bc3ee27a8dcd96:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome 79.0.3945 (Windows 10 0.0.0)     | 362  | 0    | 0    | 1m:37s | false       |
| Chrome Mobile 78.0.3904 (Android 0.0.0) | 362  | 0    | 0    | 1m:53s | false       |
| Firefox 73.0.0 (Ubuntu 0.0.0)           | 362  | 0    | 0    | 0m:58s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 362  | 0    | 0    | 0m:47s | false       |
| Mobile Safari 13.0.0 (iOS 13.0.0)       | 362  | 0    | 0    | 2m:4s  | false       |
| Safari 13.0.3 (Mac OS X 10.15.1)        | 362  | 0    | 0    | 2m:52s | false       |

### Longest running tests
- 13.065 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 11.574 secs - clone clone with noTags - _Mobile Safari_
- 10.346 secs - clone clone with noTags - _Chrome_
- 8.347 secs - clone clone with noTags - _Safari_
- 7.662 secs - clone clone with noTags - _Firefox_
- 6.817 secs - clone clone with noTags - _Chrome Mobile_
- 5.973 secs - fetch shallow fetch relative (from Github) - _Chrome Mobile_
- 5.781 secs - clone clone with noTags - _HeadlessChrome_
- 5.721 secs - Hosting Providers Azure DevOps push - _Chrome Mobile_
- 5.314 secs - fetch shallow fetch (from Github) - _Safari_
- 5.036 secs - Hosting Providers GitLab push - _Safari_

**Comment by jcubic** [comment]
I prefer semicolons but :+1: for make it the same in the code. Now I would check whole code base and check if there are no extra semicolons that are not before  `(`, not sure if there are other places were this may backfire. One of the reason why I like to always have semicolons.

**Comment by TomasHubelbauer** [comment]
I do, too, actually! I just went with the flow in this case. Good idea, I'll check the rest of the code as well but I think it has linting set up to detect semicolon discrepancies so I don't expect to find much more. Maybe other MD files and code examples on the docs site.

**Comment by wmhilton** [comment]
😆 Hmm. Maybe we should run the linter on all the examples, similarly to how I run the typechecker on all of them.

**Comment by wmhilton** [comment]
Ah. I guess I don't typecheck the example in the README. :/ Right now I just typecheck the one in JSDoc, but it would be good to extract the examples from the README and all the other markdown files in /docs...

Thanks @TomasHubelbauer !

**Pull request merged**
