### PR TITLE
Issue 347 expand oid

### LINKED ISSUE #347: New feature: expand oid
Hey,

I would like a new command to expand a given short SHA-1 to a full SHA-1.

Example:

```js
git.expandOid({ fs, dir: '.', oid: '73caa8b6' })
// => "73caa8b6f252471d0f70fdc1139dacbfcd37b843"
```

NOTE:

* Short IDs on GitHub are 7 characters
* Short IDs on GitLab are 8 characters

WDYT?

### PR DESCRIPTION
**Pull request by hsablonniere**
Fixes #347

First step towards a `expandOid` command.

* WDYT?
* How should we deal with errors?

### CODE REVIEW

**Comment by hsablonniere** [comment]
TODO:

- [ ] add TypeScript definition in `src/index.d.ts`
- [ ] handle errors
  - [ ] // TODO throw AMBIGUOUS error
  - [ ] // TODO throw NOT FOUND error
- [ ] test command
- [ ] ammend tests for errors
- [ ] add command to README list of commands
- [ ] create a new doc page [docs](https://github.com/isomorphic-git/isomorphic-git.github.io/tree/source/docs)/X.md
  - [ ] add page to the [Alphabetical Index](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/docs/alphabetic.md)
  - [ ] add page to the [sidebar](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/website/sidebars.json)

**Comment by wmhilton** [comment]
This looks good, but we need to add support for searching through packfiles, since most git commits in freshly cloned repos live in the packfile rather than in loose object form.

The packfile code is a bit of a mess... I may take this opportunity to abstract it into its own Manager rather than repeat the code that's in `GitObjectManager.read`.

**Comment by hsablonniere** [comment]
@wmhilton I rebased my branch. Looking at your comment, maybe I should let you handle the rest on this issue. WDYT?

**Comment by wmhilton** [comment]
I decided to punt refactoring `GitObjectManager`. 🤷‍♂️

**Comment by wmhilton** [comment]
Oops! I didn't update this function to use the new plugin boilerplate. Hotfix coming ASAP...

**Pull request merged**
