### PR TITLE
chore: update Karma to 3.x

### PR DESCRIPTION
**Pull request by wmhilton**

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 663f9719645a9f4a6684b5796d213e9435b5dbe2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 55.859 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 29.378 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 1 min 43.955 secs | true | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 0 | 0 | 0 | 2 mins 0.917 secs | true | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 3 mins 42.146 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 4 mins 55.528 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 663f9719645a9f4a6684b5796d213e9435b5dbe2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 1 min 27.017 secs | true | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 2 mins 52.639 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 663f9719645a9f4a6684b5796d213e9435b5dbe2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 1 min 27.39 secs | true | undefined |

**Comment by wmhilton** [comment]
Still hangs. ☹️

**Pull request closed without merging**
