### PR TITLE
chore(deps): bump simple-get from 3.0.3 to 4.0.0

### PR DESCRIPTION
**Pull request by jcubic**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

## I'm adding a parameter to an existing command X:

- [ ] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [ ] document the parameter in the JSDoc comment above the function
- [ ] add a test case in `__tests__/test-X.js` if possible
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

## I'm adding a new command:

- [ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [ ] add command to `src/index.js`
- [ ] update `__tests__/test-exports.js`
- [ ] create a test in `src/__tests__`
- [ ] document the command with a JSDoc comment
- [ ] add page to the Docs Sidebar `website/sidebars.json`
- [ ] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by 72636c** [comment]
Heya @jcubic 👋, can this be released as a `fix`?

It looks like vulnerability scanners are now flagging issues with `simple-get` <4.0.1, e.g. https://security.snyk.io/vuln/SNYK-JS-SIMPLEGET-2361683.

**Comment by jcubic** [comment]
@72636c yes I've updated simple-get but it got only updated to 4.0.0. Snyk workflow said that the PR was without vulnerabilities.

**Comment by 72636c** [comment]
@jcubic sorry for the confusion! What I meant was that the latest `isomorphic-git@1.11.0` has a dependency on `^3.0.2`, and all versions that satisfy that range are flagged as vulnerable: https://github.com/isomorphic-git/isomorphic-git/blob/v1.11.0/package.json#L64

If you cut a new release that includes this upgrade to `^4.0.0`, consumers will be able to independently update their lockfiles to pull in a patched `4.x` version (i.e. `4.0.1` or greater).

**Comment by jcubic** [comment]
Maybe I did something wrong with this PR, the release is automatic. I've updated the version already.

**Comment by mojavelinux** [comment]
The release is handled by the [semantic-release](https://github.com/semantic-release/semantic-release) package. I don't think "chore" in the commit message triggers a release.

**Comment by jcubic** [comment]
@mojavelinux thanks. So it seems that those vunerability PRs from Dependabot are useless if they don't release a new version.

@72636c Added another PR with a fix in README and updated package.json to include 4.0.1 #1474

**Comment by mojavelinux** [comment]
Indeed. Though I think the commit message it looks for is configurable, so it seems possible to get it to work this way.

**Pull request merged**
