### PR TITLE
chore(deps): Replace deprecated Ubuntu 18.04 image with 22.04

### PR DESCRIPTION
**Pull request by seanpoulter**
## I'm updating a dependency

This PR updates the Ubuntu image in the pipeline. Ubuntu 18.04 has been deprecated and will be removed on December 1st. See [these release notes](https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-208-update#announcing-deprecation-of-ubuntu-1804-images-updated) for more.

There is a warning in the pipeline as well (3rd card):

Screen Shot 2022-11-23 at 20 16 06

### CODE REVIEW

**Comment by seanpoulter** [comment]
Ah, right, we have those intermittent test failures in the pipeline using BrowserStack or SauceLabs. I think we've seen the base image change works, despite the tests failing. I'd say merge as is and we can try updating those npm packages to see if they're more stable. 🤞

**Comment by jcubic** [comment]
I'm hesitant to merge this, PR build is exactly the same as the release if here is failing the release will also fail.

**Comment by jcubic** [comment]
There are random failing tests from BrowserStack I will contact their support. I have an account there but I don't have access to the isomorphic-git repo (I use to form my other project). Will also try to contact @wmhilton so he can give me access.

**Comment by jcubic** [comment]
I've updated the karma file, can you update your branch (rebase or merge with the main branch) we will see if the test passes. I've found the linked issue where BrowserStack suggested settings for the Karma plugin.

**Comment by seanpoulter** [comment]
Thanks for updating the Karma file @jcubic. The pipeline passed. 🎉 
I noticed this while I was watching. I'll copy it in the PR I was using to track the dependency updates.

image

It looks like Safari successfully restarted in this run too:
image

The first pipeline failed though. I'll try to rerun it ...
https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=2974&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b

**Comment by jcubic** [comment]
Ok but the PR job is still failing. I will not merge this because we will have a broken job for every new PR and probably also release.

**Comment by mojavelinux** [comment]
I really think that if you are going to be spending all this time to fix the build, that the workflow should be moved to GitHub Actions where it is easier to manage. Part of the problem with the build is that so few people are familiar with how to use and access builds on Azure. So this seems like the right time to address that. Just a suggestion.

**Comment by seanpoulter** [comment]
Sounds like a plan @mojavelinux. I'd propose we fix the flaky tests first then migrate to GitHub Actions.

@jcubic mentioned the tests were failing or flaky locally too so I've laid the foundation to shake that out as well. Here's the split for all 70/1000 test failures.

### Flaky tests

| Failure Mode | Frequency | Issue |
| - | - | - |
| create signed commit : failed | 11 | #1686  |
| creates a signed tag to HEAD : failed | 6 | #1687 |

### Flaky "environment"

| Failure Mode | Frequency |
| - | - |
| Disconnected | 34 |
| ChromeHeadless crashed | 33 |
| shallow fetch (from GitHub) : failed | 1 |
| by hash (from GitHub) :  failed | 1 |

**Pull request closed without merging**
