### PR TITLE
fix(fetch): don't throw a TypeError if resp missing capabilities line

### LINKED ISSUE #911: TypeError is thrown during clone when permission is denied to repository on BitBucket
A TypeError is thrown during clone under the following circumstances:

* The repository is hosted on Bitbucket.
* The credentials (user:password) must be valid for an existing account on the server.
* The account must not have access permission to the repository.

The problem seems to be in the capabilities negotiation.

Here's the stack from the error:

```
Caused by: TypeError: Cannot read property 'split' of undefined
    at parseRefsAdResponse (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5123:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.discover (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5241:26)
    at async fetchPackfile (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6041:22)
    at async fetch (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5902:22)
    at async Object.clone (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6413:42)
```

### PR DESCRIPTION
**Pull request by wmhilton**
fixes #911 possibly? alternative to #922 possibly?

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 8d99dff1f9b86d5b1651e839b72731106071df6b:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 3m:36s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 4m:14s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 1m:55s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:50s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 3m:32s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:45s | false       |

### Longest running tests
- 34.449 secs - fetch fetch (from Github) - _Edge_
- 30.737 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 17.691 secs - fetch shallow fetch (from Github) - _Edge_
- 16.722 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 12.953 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 12.526 secs - fetch shallow fetch since (from Github) - _Edge_
- 12.128 secs - fetch fetch (from Github) - _Firefox_
- 11.543 secs - fetch shallow fetch relative (from Github) - _Edge_
- 10.881 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 10.027 secs - GitPackIndex from .pack - _Firefox_
- 9.53 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_

**Comment by mojavelinux** [comment]
This fix seems like it would do the trick. Though I might go a little deeper. If the `\x00` is missing, then perhaps assume that the line is some sort of error message and throw it as a git server response fail. Chances are, if `\x00` is missing, this isn't even a firstRef/capabilities line at all.

**Comment by wmhilton** [comment]
Closing in favor of #922. After all, it _is_ a violation of the [protocol](https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt):

> The returned response is a pkt-line stream describing each ref and
> its known value.  The stream SHOULD be sorted by name according to
> the C locale ordering.  The stream SHOULD include the default ref
> named `HEAD` as the first ref.  The stream MUST include capability
> declarations behind a NUL on the first ref.

and since the HTTP status code in #911 was 200, if we did't throw an error from parsing there would be no signal at all there was an error.

**Comment by mojavelinux** [comment]
Nice!

**Pull request closed without merging**
