### PR TITLE
feat: Get remote tracking

### PR DESCRIPTION
**Pull request by crutchcorn**
# I'm adding a new command:

This PR adds the `getRemoteTracking` command per #233

- [x] add as a new file in `src/api` (and `src/commands` if necessary)
- [x] add command to `src/index.js`
- [x] update `__tests__/__snapshots__/test-exports.js.snap`
- [x] create a test in `src/__tests__`
- [x] document the command with a JSDoc comment
- [x] add page to the Docs Sidebar `website/sidebars.json`
- [x] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by crutchcorn** [comment]
Hey @wmhilton am I able to get a review on this sometime soon? I'm hoping that I can stop using GitHub as my `isomorphic-git` versioning and be able to use the published NPM version 😅

**Comment by crutchcorn** [comment]
Pinging again as I see @wmhilton active

**Comment by wmhilton** [comment]
How are you using this in GitShark exactly? Because this... doesn't exactly do something intuitive to me. It doesn't get the remote branch that corresponds to a local branch, it gets the local tracking branch that corresponds to a remote branch name. In other words, it doesn't tell you what branch on the remote will be fetched if you did git pull on the current HEAD branch, it tells you which branch in `refs/remotes` will be updated if you fetched a particular branch from the remote.

I hesitate to merge this as is, because even I was confused at first. If this _is_ exactly what you intended... I can probably include it. I think we should rename `ref` to `remoteRef` though. And rather than searching through all the remotes make users specify the `remote`.

**Comment by crutchcorn** [comment]
Oh. That's a misunderstanding on my part, admittedly. I'm still doing my best to learn the internals - so there's bound to be some misunderstandings on my part. How do we update to make the behavior match what you would expect?

**Comment by crutchcorn** [comment]
Closing as the behavior doesn't match what we're looking to do

**Pull request closed without merging**
