### PR TITLE
perf(push): send thin packs when possible

### LINKED ISSUE #1134: `push` sends too many files/objects
Hey William and isomorphic-git team :wink:

We are going through a major update on our CLI at Clever Cloud (0.37.0 to latest) and we encountered some perf problems.

One of those problems concerns `push` and what `listObjects` prepares for the push.

## Test context

We ran our tests on 2 projects:

Thank you `git-sizer`

* repo WWW
  * 2.2k commits
  * 10.7k trees
  * 164k tree entries
  * 4.7k blobs
  * 4.7 MiB for biggest blob
* repo CONSOLE
  * 3.4k commits
  * 14.8k trees
  * 266k tree entries
  * 8.1k blobs
  * 443 KiB for biggest blob

We timed the execution of a `push` in this situation:

Pushing only one commit which only contains a small change on one file.

## Tests results

* We added timers around main steps of `push` and a log on `listObjects` output.
* `objects.size` was 1761 to push only one new commit with just one modified file.
* `listObjects` took 70 millisecs
* `_pack` took 11 secs
* `GitRemoteHTTP.connect` took 27 secs
* the whole push took 42 secs

## Proposed solution

We think `push` should only pack and send objects corresponding to files that don't exist yet on the remote repo.

To do this, we naïvely list objects from the merge base commit because remote should already have those objects and remove them from the list.

:tada: This was a major improvement:

With project WWW, in the only one commit to push with 1 modified filed:

* Only 1 object was sent instead of 1761
* `_pack` took 14 millisecs
* `GitRemoteHTTP.connect` took 88 millisecs

### PR DESCRIPTION
**Pull request by hsablonniere**
This is a very naïve proposition to fix #1134. It works on the two projects we tried it on but it's just a conversation starter on how to fix this.

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for fe44b5a47766326ecbf2a32f0454ebedbd8570e4:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome 79.0.3945 (Windows 10 0.0.0)     | 363  | 0    | 0    | 2m:37s | false       |
| Chrome Mobile 80.0.3987 (Android 0.0.0) | 363  | 0    | 0    | 1m:54s | false       |
| Firefox 76.0.0 (Ubuntu 0.0.0)           | 363  | 0    | 0    | 1m:0s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 363  | 0    | 0    | 0m:49s | false       |
| Mobile Safari 13.0.0 (iOS 13.0.0)       | 363  | 0    | 0    | 2m:51s | false       |
| Safari 13.0.3 (Mac OS X 10.15.1)        | 363  | 0    | 0    | 3m:29s | false       |

### Longest running tests
- 11.701 secs - clone clone with noTags - _Chrome_
- 11.141 secs - clone clone with noTags - _Mobile Safari_
- 8.987 secs - clone clone with noTags - _Safari_
- 8.398 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome_
- 8.326 secs - clone clone with noTags - _Firefox_
- 7.682 secs - walk can populate type, mode, oid, and content - _Safari_
- 7.477 secs - clone clone with noTags - _Chrome Mobile_
- 7.169 secs - fetch fetch --prune from git-http-mock-server - _Safari_
- 6.719 secs - fetch fetch --prune-tags from git-http-mock-server - _Mobile Safari_
- 6.578 secs - clone clone with noTags - _HeadlessChrome_
- 5.758 secs - statusMatrix statusMatrix with filter - _Safari_

**Comment by wmhilton** [comment]
Sorry, I got side tracked trying to solve a related problem: how to only send "new" commits to the remote. It gets tricky because of merge commits. The current solution of stopping commit traversing at merge bases fails in some common cases such as this:

```
* fe44b5a - (improve-push-list-objects) don't run listObjects on every single branch, just on the merge bases (8 hours ago)
*   a9a00f0 - Merge branch 'master' into improve-push-list-objects (9 hours ago)
|\
| * 7864c33 - (tag: v1.4.1, origin/master, origin/HEAD, master) perf(push, findMergeBase): improve find merge base speed (#1132) (9 hours ago)
| * a4bd6e8 - broken link to cors-proxy on npm (#1133) (34 hours ago)
* | 3d4ef6c - fix(push): only send "new" objects to remote (3 weeks ago)
|/
* 50ece1a - (yet-again-no-buffers) noGitSuffix is no longer required (#1112) (6 weeks ago)
```

Here, the smart thing to do would be to push 3 commits (fe44b5a, a9a00f0, and 3d4ef6c), but isomorphic-git instead would push 919 commits because the merge base of the two branches (7864c33) only exists on one side of the split path, and traversing continues down the other path.

I think I've solved it though! I'll clean up my work tomorrow.

**Comment by wmhilton** [comment]
> I'll clean up my work tomorrow.

So... I have some reservations about my algorithm to send fewer commits... the worst case scenario has pretty bad time complexity, and the code is also complex so I'm worried it might introduce a bug and upload incomplete data. 😱 It'll still need some ironing out.

But *this* PR as it is already will make a big difference in situations where you are pushing to an existing branch, like this:

```
* 41afcf1 - (HEAD -> test-234) add console.logs (4 minutes ago)
* fe44b5a - (origin/test-234) don't run listObjects on every single branch, just on the merge bases (30 hours ago)
```

It reduces the # of objects sent from 1708 to 5 (`push.js` blob, `commands` tree, `src` tree, root tree, and the commit object).

And that's a very common scenario I think - modifying a few files on an existing branch and pushing to that same branch. Certainly that's the case in Stoplight Studio so it should help reduce the upload size there a bunch.

**Comment by wmhilton** [comment]
The main difference between the current code in the PR and your original, is that I'm only skipping objects in the merge base (if one was found) whereas you were skipping objects from all of the commits in `finish` which is every single remote branch. That made me a little nervous, because that grows linearly with the number of branches, and there's no guarantee that the local repo has those commits. (I could have added error handling... but then it'd be another thing to test carefully.)

I think there's definitely room to improve it... one idea I had is to also exclude objects from the `default` branch (`refs/remotes/{remote}/HEAD`) if that exists... actually hang on let me do that, because that should help tremendously in a lot of cases.

**Comment by karma-pr-reporter** [comment]
## Test Results for 4411e8dabae24e85a2401a719c141b38c51d788c:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome 79.0.3945 (Windows 10 0.0.0)     | 363  | 0    | 0    | 3m:8s  | false       |
| Chrome Mobile 80.0.3987 (Android 0.0.0) | 363  | 0    | 0    | 1m:54s | false       |
| Firefox 76.0.0 (Ubuntu 0.0.0)           | 363  | 0    | 0    | 0m:56s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 363  | 0    | 0    | 0m:40s | false       |
| Mobile Safari 13.0.0 (iOS 13.0.0)       | 363  | 0    | 0    | 2m:12s | false       |
| Safari 13.0.3 (Mac OS X 10.15.1)        | 363  | 0    | 0    | 2m:7s  | false       |

### Longest running tests
- 10.685 secs - clone clone with noTags - _Chrome_
- 9.047 secs - clone clone with noTags - _Mobile Safari_
- 8.948 secs - clone clone with noTags - _Firefox_
- 6.863 secs - fetch fetch --prune from git-http-mock-server - _Chrome_
- 6.797 secs - clone clone with noTags - _Chrome Mobile_
- 6.734 secs - clone clone with noTags - _HeadlessChrome_
- 6.5 secs - walk can populate type, mode, oid, and content - _Chrome_
- 6.431 secs - clone clone with noTags - _Safari_
- 6.244 secs - fetch shallow fetch relative (from Github) - _Chrome Mobile_
- 6.224 secs - statusMatrix statusMatrix with filepaths - _Chrome_
- 5.077 secs - Hosting Providers GitHub push - _Chrome_

**Comment by wmhilton** [comment]
The nice thing about that is it's a fixed cost. So at worst we run `listObjects` twice rather than N times. There still could be situations where the performance is now horribly worse... if you have a `master` branch with millions of directories and a docs branch with only a dozen, pushing the docs branch will now trigger a million calls to `readObject` for absolutely no benefit since none of the objects in the `master` branch and the `docs` branch overlap. _But_ if you make a new branch off of `master` where you only change one file, you'll actually be able to push that new branch to the remote without sending a million objects.

I suppose I could solve that by making `listObjects` smarter... there's no reason for it to list out a million objects from `master` if the directory structure is completely different from `docs`. But I think I'll wait until someone actually runs into this issue before optimizing for it.

**Comment by wmhilton** [comment]
Oh! I forgot tell tell you. Fun fact, these packfiles that skip objects that the recipient already has are called "thin packs". https://git-scm.com/docs/protocol-capabilities#_thin_pack

**Pull request merged**
