### PR TITLE
chore(deps-dev): bump karma, jasmine, and related dependencies

### PR DESCRIPTION
**Pull request by seanpoulter**
## Dependencies

This PR should be reviewed after #1538.

## I'm updating a dependency

This PR will hopefully improve the CI pipeline stability by updating Karma and the related packages. In this PR we:

- bump karma from 2.0.5 to 6.3.18
- bump karma-browserstack-launcher from 1.5.1 to 1.6.0
- bump karma-chrome-launcher from 3.1.0 to 3.1.1
- bump karma-firefox-launcher from 1.2.0 to 2.1.2
- bump karma-jasmine bump from 2.0.1 to 5.0.0
- bump karma-junit-reporter from 1.2.0 to 2.0.1
- bump jasmine-core from 3.4.0 to 3.99.1
- Update two assertions that compare an `ArrayBuffer` using @strangedev's fix from 5c38fe61a783808d779207490fc6459319130711 in [#1386](https://github.com/isomorphic-git/isomorphic-git/pull/1386).

### Don't worry about the Breaking Changes

I have reviewed the release notes for each package. The following is a summary of how we are **not affected** by the breaking changes.

--

We are not affected by the breaking changes to `karma`:

- karma v3.0.0 drops support for Node.js v4
- karma v4.0.0 drops support for Node.js v6
- karma v5.0.0 drops support for Node.js v8, Bluebird promises (not used), and createPreprocessor (not used)
- karma v6.0.0 drops support for `server.start()` (not used), `customFileHandlers` (not used), and `customScriptTypes` (not used)

We are not affected by breaking changes to `karma-firefox-launcher`:

- karma-firefox-launcher v2.0.0 drops support for Node.js v8

We are not affected by breaking changes to `karma-jasmine`:

- karma-jasmine v3.0.0:
    - drops support for Node.js v6 and `stopOnFailure` (not used)
    - requires jasmine@^3.3.0 as a peer dependency (installed)
- karma-jasmine v4.0.0 drops support for Node.js v8
- karma-jasmine v5.0.0:
    - drops support for Node.js v10
    - requires karma ^6.0.0 (installed)

We are not affected by breaking changes to `karma-junit-reporter`:

- karma-junit-reporter v2.0.0 drops support for Node.js v6

We have not updated to `jasmine-core` v4 because we may be affected by browser compatibility issues.

### Related PRs

This PR closes:

- #1533
- #1528

This PR will also cause merge conflicts with:

- #1386

### Test Plan

- `npm test` passes locally
- It passes in CI

### CODE REVIEW

**Comment by jcubic** [comment]
Tests are failing, it seems they came from Android:
```
Chrome 99.0.4844.73 (Android 10) LOG: ApiError{syscall: '', errno: 95, code: 'ENOTSUP', path: undefined, stack: 'Error
    at new ApiError (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:24060:22)
    at UnlockedOverlayFS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:26771:8)
    at http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33933:20
    at Mutex.lock (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33592:5)
    at OverlayFS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33932:14)
    at FS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:25329:31)
    at Object._fsMock.<computed> [as symlink] (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:25636:28)
    at http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:32053
    at new Promise (<anonymous>)
    at f.<anonymous> ([http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:31893)',](http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:31893)%27,) message: 'Error: ENOTSUP: Operation is not supported.'}
18 04 2022 02:29:01.983:INFO [Chrome 99.0.4844.73 (Android 10) | clone | should set up the remote tracking branch by default]: ApiError{syscall: '', errno: 95, code: 'ENOTSUP', path: undefined, stack: 'Error
    at new ApiError (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:24060:22)
    at UnlockedOverlayFS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:26771:8)
    at http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33933:20
    at Mutex.lock (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33592:5)
    at OverlayFS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:33932:14)
    at FS.symlink (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:25329:31)
    at Object._fsMock.<computed> [as symlink] (http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:25636:28)
    at http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:32053
    at new Promise (<anonymous>)
    at f.<anonymous> ([http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:31893)',](http://localhost:9876/base/__tests__/index.webpack.js?54bb7d4ba2dd4fb92a8811e31a3dfc00e6c38d99:15813:31893)%27,) message: 'Error: ENOTSUP: Operation is not supported.'}
```

**Comment by jcubic** [comment]
It may be related to #1446 but not sure why only Android is failing.

**Comment by seanpoulter** [comment]
Thanks @jcubic. Those `ApiError`s occur for all browsers even when I run locally. They're not reported as test failures:

image

I think the problem is some of the tests did not start in the remote browsers. Have you seen this before? It could be the changes to `karma-sauce-launcher`:

image

Could you try restarting the pipeline? If it fails I'll try reverting the changes to `karma-sauce-launcher`.

**Comment by jcubic** [comment]
No, I've never seen something like this before. I've restarted the job.

**Comment by jcubic** [comment]
Still failing.

**Comment by seanpoulter** [comment]
Thanks @jcubic. Before I spend too much time troubleshooting Sauce Labs I'll remove the changes to `karma-sauce-launcher` and see if it'll still work.

**Comment by seanpoulter** [comment]
Wow, the CI pipeline passed. 🎉  I'd suggest merging #1538 first. I forked this branch from it.

**Pull request merged**
