### PR TITLE
fix: avoid unnecessary match if emitter is not defined

### PR DESCRIPTION
**Pull request by mojavelinux**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by mojavelinux** [comment]
I wonder if we could avoid the call to response.progress entirely if emitter is not set.

**Comment by karma-pr-reporter** [comment]
## Test Results for 97e45d9d280cccc9dd3a0f1d4aa58b5d0f64d236:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 1 | 55.446 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 223 | 1 | 0 | 1 min 36.798 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 223 | 1 | 0 | 3 mins 2.21 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 1 | 3 mins 20.858 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 223 | 1 | 0 | 3 mins 53.095 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 223 | 1 | 0 | 4 mins 50.165 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 97e45d9d280cccc9dd3a0f1d4aa58b5d0f64d236:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 223 | 1 | 0 | 44.541 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 223 | 1 | 0 | 2 mins 49.369 secs | false | undefined |

**Comment by wmhilton** [comment]
Nice. Makes code a little cleaner and faster (presumably). :)

**Comment by karma-pr-reporter** [comment]
## Test Results for 8f16f0367f4a0f08ae902f2fb3f146534dc36934:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 223 | 1 | 0 | 56.243 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 223 | 1 | 0 | 1 min 38.303 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 223 | 1 | 0 | 3 mins 7.392 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 223 | 1 | 0 | 3 mins 42.203 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 222 | 1 | 1 | 4 mins 21.027 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 223 | 1 | 0 | 4 mins 50.45 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8f16f0367f4a0f08ae902f2fb3f146534dc36934:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 223 | 1 | 0 | 4 mins 15.216 secs | false | undefined |

**Pull request merged**
