### PR TITLE
fix: listRemotes function return type was incorrect.

### PR DESCRIPTION
**Pull request by dsabanin**
It looks like there were two interfaces defined by mistake with the same name `RemoteDescription`, and that name is used in return type for `listBranches()` and `getRemoteInfo()` functions. According to the code, only one of the `RemoteDescription` types is correct for `listBranches()` function. 

I renamed the one that `listBranches()` returns to `RemoteDefinition` (as a set of url and name defines the remote, but does not describe it in detail), and left `RemoteDescription` type as a return for `getRemoteInfo()`.

Looks like it was a simple mixup.

## I'm fixing a bug or typo

- [X] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for fe0915c7f0d6f4b2f44ac7d73a391bdd4f7bc35b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 247 | 1 | 0 | 1 min 14.625 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 247 | 1 | 0 | 2 mins 27.504 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 2 mins 42.577 secs | true | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 247 | 1 | 0 | 3 mins 51.205 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 247 | 1 | 0 | 4 mins 19.559 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 247 | 1 | 0 | 4 mins 57.345 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for fe0915c7f0d6f4b2f44ac7d73a391bdd4f7bc35b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 247 | 1 | 0 | 5 mins 29.758 secs | false | undefined |

**Comment by wmhilton** [comment]
Yup. The perils of writing TS definitions for a non-TS project. So easy to make mistakes!

**Comment by karma-pr-reporter** [comment]
## Test Results for 27cfea80f7f183c78dc87f7ac87cc0a610528ab4:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 247 | 1 | 0 | 1 min 15.689 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 247 | 1 | 0 | 2 mins 29.303 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 247 | 1 | 0 | 3 mins 53.611 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 247 | 1 | 0 | 3 mins 59.245 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 247 | 1 | 0 | 5 mins 0.583 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 247 | 1 | 0 | 6 mins 13.039 secs | false | undefined |

**Pull request merged**
