### PR TITLE
feat: Rename branch

### LINKED ISSUE #39: moveBranch

### PR DESCRIPTION
**Pull request by crutchcorn**
## I'm adding a new command:

This PR implements the `renameBranch` feature (also noted as the `moveBranch` feature in #39. If I need to rename this function to `moveBranch` I would be willing to do so).

- [x] add as a new file in `src/api` (and `src/commands` if necessary)
- [x] add command to `src/index.js`
- [x] update `__tests__/__snapshots__/test-exports.js.snap`
I'm not sure how to do this, help!
- [x] create a test in `src/__tests__`
- [x] document the command with a JSDoc comment
- [x] add page to the Docs Sidebar `website/sidebars.json`
- [x] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
I am avoiding doing this until the code has been reviewed/approved to avoid causing problems with merge conflicts
- [x] squash merge the PR with commit message "feat: Added 'X' command"

closes #39

### CODE REVIEW

**Comment by crutchcorn** [comment]
@wmhilton it seems that the build is failing due to an linting rule. However, while running `yarn nps lint`, I don't get the linting error that CI seems to be throwing (although I do get other linting errors):

<details>
  <summary>Linting errors</summary>
```
​C:\Users\crutchcorn\git\GitGui\isomorphic-git [renameBranch ≡]
λ  yarn nps lint
yarn run v1.22.4
$ C:\Users\crutchcorn\git\GitGui\isomorphic-git\node_modules\.bin\nps lint
nps is executing `lint` : eslint .

C:\Users\crutchcorn\git\GitGui\isomorphic-git\cli.js
  4:20  error  `minimisted` import should occur after import of `./http/node`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\package-scripts.js
  5:13  error  `./package.json` import should occur before import of `nps-utils`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\api\writeRef.js
  2:1  error  `clean-git-ref` import should occur after import of `../utils/join.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\commands\addRemote.js
  4:1  error  `clean-git-ref` import should occur after import of `../managers/GitConfigManager.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\commands\branch.js
  4:1  error  `clean-git-ref` import should occur after import of `../managers/GitRefManager.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\commands\pack.js
  1:1  error  `sha.js/sha1.js` import should occur after import of `../utils/padHex.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\http\node\index.js
  1:1  error  `simple-get` import should occur after import of `../../utils/fromNodeStream.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\managers\GitIgnoreManager.js
  1:1  error  `ignore` import should occur after import of `../utils/join.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\managers\GitIndexManager.js
  2:1  error  `async-lock` import should occur after import of `../utils/compareStats.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\managers\GitShallowManager.js
  3:1  error  `../utils/join.js` import should occur before import of `async-lock`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\models\FileSystem.js
  1:1  error  `pify` import should occur after import of `../utils/dirname.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\models\GitPackIndex.js
  1:1  error  `crc-32` import should occur after import of `./GitObject`           import/order
  2:1  error  `git-apply-delta` import should occur after import of `./GitObject`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\utils\git-list-pack.js
  4:1  error  `pako` import should occur after import of `../utils/StreamReader.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\src\utils\shasum.js
  4:1  error  `./toHex.js` import should occur before import of `sha.js/sha1.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\__tests__\test-log.js
  2:17  error  There should be at least one empty line between import groups                                  import/order
  2:17  error  `@isomorphic-git/pgp-plugin` import should occur after import of `./__helpers__/FixtureFS.js`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\__tests__\__helpers__\fix-version-number.js
  4:11  error  `../../package.json` import should occur before import of `replace-in-file`  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\__tests__\__helpers__\FixtureFS\makeBrowserFS.js
  1:24  error  There should be at least one empty line between import groups  import/order

C:\Users\crutchcorn\git\GitGui\isomorphic-git\__tests__\__helpers__\generate-docs.js
  7:13  error  `../..` import should occur before import of `jsdoc-api`  import/order

✖ 20 problems (20 errors, 0 warnings)
  19 errors and 0 warnings potentially fixable with the `--fix` option.

The script called "lint" which runs "eslint ." failed with exit code 1 https://github.com/sezna/nps/blob/v5.9.8/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

Seems there may be a mismatch for local dev vs. CI linting?

**Comment by wmhilton** [comment]
If @isomorphic-git-bot is still working, it'll fix the linting errors for us! And if not... I'll have to fix the bot I guess. 😂

Super excited! It's after midnight my time so I won't get to this tonight, but tomorrow evening I will for sure! And I know I need to investigate that react native Blob / Decompression Stream thing too, that's been sitting on my desk for a while now 😬

**Comment by wmhilton** [comment]
Hmm. :( Looks like glitch.com is finally living up to it's name.

image

I guess it's time to port the isomorphic-git-bot to a GitHub Action or whatever the latest hotness is.

**Comment by wmhilton** [comment]
> - [ ] update __tests__/__snapshots__/test-exports.js.snap
> I'm not sure how to do this, help!

Oh no! It's deceptively simple: you open `__tests__/__snapshots__/test-exports.js.snap` and add the name of your exported function, in the right alphabetical order. 😆 At least that's how I do it. It's a weird test, but is designed to keep me from "accidentally" exporting internal/experimental functions (or accidentally deleting a line that exports something).

**Comment by wmhilton** [comment]
Alrighty, weird problem: tests pass fine in Jest but they seem a little flaky in the browsers... having to past this myself since my poor bot is broke:

```

### Erroring Tests

- HeadlessChrome 0.0.0 (Linux 0.0.0):
  - branch rename branch and checkout
- Firefox 77.0.0 (Ubuntu 0.0.0):
  - Hosting Providers Azure DevOps push
  - branch rename branch and checkout
- Chrome Mobile 80.0.3987 (Android 0.0.0):
  - branch rename branch and checkout
- Safari 13.1.0 (Mac OS X 10.15.4):
  - branch rename branch and checkout
- Chrome 79.0.3945 (Windows 10 0.0.0):
  - branch rename branch and checkout
- Mobile Safari 13.0.0 (iOS 13.0.0):
  - branch rename branch and checkout

```

(the Azure DevOps one is likely flake)

Investigating....

**Comment by wmhilton** [comment]
So good news and bad news. Good news is your code looks great! I think `renameBranch` is a splendid name for it, etc.

Bad news is I think there's a race condition in how Jasmine and LightningFS are dealing with `makeFixture`. Some of the time, the fixture from `rename branch` test isn't cleaned up before the `rename branch and checkout` test runs, resulting in a `NotFoundError`. 😢 At least that's my theory. Kinda weird it hadn't shown up before and I'd convinced myself there weren't race conditions but hey, you discover something new every day.

🤔 On the bright side... I've thought of a workaround! 😆

**Comment by crutchcorn** [comment]
Love the workaround haha. Thanks so much for getting this one in so quickly! :D

**Comment by wmhilton** [comment]
Ahhhhhh. It hasn't been on the docs website because we didn't actually do these steps:
- add page to the Docs Sidebar website/sidebars.json
- add page to the v1 Docs Sidebar website/versioned_sidebars/version-1.x-sidebars.json

but also the docs website hasnt' been updating because I forgot to switch GH Pages to build from `main` instead of `master` oops.

Anyway, your command should appear in the docs soon!!!

**Comment by crutchcorn** [comment]
I hate bothering @wmhilton - but is there any way I could get some of my other PRs reviewed/merged? I'm still having to use a fork for my projects because of them not being merged which isn't a great look for production 😅

**Comment by wmhilton** [comment]
> which isn't a great look for production 😅

Well, I've found it's the new normal. The company I work for has lots of forks of OSS packages in prod. But I'll try to review them this weekend. 👍

**Pull request merged**
