### PR TITLE
fix: consolidate ref filter in fetchPackfile

### PR DESCRIPTION
**Pull request by mojavelinux**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 0dbf7ceb4c970f17089099167d406f1a6e61f630:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 225 | 1 | 0 | 56.508 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 225 | 1 | 0 | 1 min 31.197 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 225 | 1 | 0 | 2 mins 41.838 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 225 | 1 | 0 | 3 mins 0.794 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 225 | 1 | 0 | 3 mins 28.855 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 225 | 1 | 0 | 4 mins 24.211 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for bba2ac4a90326b1bd0b5d00f06271a3380c4e6da:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 225 | 1 | 0 | 56.594 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 225 | 1 | 0 | 1 min 34.839 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 225 | 1 | 0 | 2 mins 58.327 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 225 | 1 | 0 | 3 mins 15.345 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 225 | 1 | 0 | 3 mins 51.051 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 225 | 1 | 0 | 4 mins 23.457 secs | false | undefined |

**Comment by wmhilton** [comment]
> I'm wondering if it's ever necessary to go back to the original map of refs for any reason, or whether we can assume everything we need will be in the curated refs.

I'm confident we can assume everything we need will be in the curated refs, which is exactly why I modify the original in the first place rather than create a new object and copy everything over. 😉

**Comment by mojavelinux** [comment]
> I'm confident we can assume everything we need will be in the curated refs

Ah! That's what I needed to know. Okay, then I'll cut out the local var.

**Comment by karma-pr-reporter** [comment]
## Test Results for a0b5af0b8ead3453ab9b4281495015c07fff0ea3:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 225 | 1 | 0 | 55.211 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 225 | 1 | 0 | 1 min 29.546 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 225 | 1 | 0 | 2 mins 29.702 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 225 | 1 | 0 | 3 mins 32.905 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 225 | 1 | 0 | 6 mins 11.886 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 225 | 1 | 0 | 9 mins 52.82 secs | false | undefined |

**Comment by wmhilton** [comment]
LGTM!

**Comment by karma-pr-reporter** [comment]
## Test Results for a76467a5c09841db9d1166db8e4ad922d9d5cfa3:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 226 | 1 | 0 | 59.92 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 226 | 1 | 0 | 1 min 38.606 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 226 | 1 | 0 | 2 mins 18.303 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 226 | 1 | 0 | 4 mins 28.121 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 226 | 1 | 0 | 5 mins 14.963 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 226 | 1 | 0 | 5 mins 56.025 secs | false | undefined |

**Comment by mojavelinux** [comment]
\o/

**Pull request merged**
