### PR TITLE
[feat:stash] add stash API for push, apply, pop, drop, list and clean #228 #980

### PR DESCRIPTION
**Pull request by modesty**
## I'm adding a new command: stash

- [✅ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [✅ ] add command to `src/index.js`
- [ ✅] update `__tests__/test-exports.js`
- [ ✅] create a test in `src/__tests__` - test-stash covers 22 test cases
- [ ✅] document the command with a JSDoc comment
- [ ✅] add page to the Docs Sidebar `website/sidebars.json`
- [ ✅]] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ✅]] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by jcubic** [comment]
Please rebase, the filing test got disabled.

**Comment by modestysn** [comment]
rebase pushed

**Comment by jcubic** [comment]
Thanks, I will need to test the feature locally before merging. This is a big feature I want to make sure it works correctly. Will do this probably tomorrow and will take a closer look at the code.

I'm not sure if the tests pass now. I'm using a mobile GitHub app.

**Comment by jcubic** [comment]
It seems there are failing tests

**Comment by jcubic** [comment]
There are some failing tests, you need to figure that out before this will be merged.

https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=3381&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b

I'm not sure what is the issue, but failing tests are for git stash.

**Comment by modesty** [comment]
tests with Jest are all good, only Karma fails. It's caused by `makeFixture`: it returns different `dir` when invoked from different test cases with Jest, but when run with karma, it returns the same `dir`, which causes stashed/applied files interfere each other. I'll try to correct it when get a chance.

**Comment by modesty** [comment]
https://github.com/isomorphic-git/isomorphic-git/pull/1898 replaces this one for a cleaner history, build and test

**Pull request closed without merging**
