### PR TITLE
fix(types): type of isDescendent depth argument should be number, not string

### PR DESCRIPTION
**Pull request by c-w**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

---

According to the jsDoc type annotations, the `depth` argument for the `isDescendent` function is an optional number:

https://github.com/isomorphic-git/isomorphic-git/blob/30fddf7373ca33cee599e1cbc98f55144e3e0afa/src/commands/isDescendent.js#L20

However, the Typescript typings file declares the argument as an optional string which causes `tsc` to fail:

https://github.com/isomorphic-git/isomorphic-git/blob/30fddf7373ca33cee599e1cbc98f55144e3e0afa/src/index.d.ts#L475

This pull request makes the jsDoc and Typescript typings consistent.

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for ee99c2667f8fd1e12fd497c8200c9a94eab725b7:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 3m:18s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 4m:15s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 1m:55s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:51s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 3m:50s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:49s | false       |

### Longest running tests
- 32.431 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 21.574 secs - fetch fetch (from Github) - _Firefox_
- 20.371 secs - fetch fetch (from Github) - _Edge_
- 18.016 secs - fetch shallow fetch (from Github) - _Firefox_
- 17 secs - fetch shallow fetch relative (from Github) - _Edge_
- 16.166 secs - GitPackIndex to .idx file from .pack - _Edge_
- 14.719 secs - GitPackIndex from .pack - _Edge_
- 12.785 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 11.524 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 10.196 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 9.621 secs - fetch shallow fetch (from Github) - _Edge_

**Comment by wmhilton** [comment]
Oh! Nice! Ya nailed it. ❤️ 
18 days... man I should activate the beta of the new GitHub Notifications UX.

**Comment by karma-pr-reporter** [comment]
## Test Results for 78ad45bcfd3d5b04cff207d39fb5a5d964067f25:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 316  | 1    | 0    | 3m:12s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 316  | 1    | 0    | 4m:18s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 316  | 1    | 0    | 1m:55s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 316  | 1    | 0    | 0m:51s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 248  | 2    | 0    | 4m:49s | true        |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 315  | 1    | 1    | 3m:50s | false       |

### Erroring Tests

- Safari 11.1.2 (Mac OS X 10.13.6):
  - commit pgp plugin signing - backwards compatiblity

### Longest running tests
- 25.01 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 21.967 secs - fetch fetch (from Github) - _Edge_
- 18.811 secs - fetch shallow fetch (from Github) - _Edge_
- 17.188 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 16.586 secs - GitPackIndex from .pack - _Edge_
- 16.089 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 15.267 secs - GitPackIndex to .idx file from .pack - _Edge_
- 12.18 secs - fetch fetch (from Github) - _Firefox_
- 11.785 secs - fetch shallow fetch (from Github) - _Firefox_
- 10.263 secs - fetch shallow fetch since (from Github) - _Edge_
- 9.375 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 78ad45bcfd3d5b04cff207d39fb5a5d964067f25:
| Browser                           | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 315  | 2    | 0    | 3m:48s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)  | 316  | 1    | 0    | 3m:38s | false       |

### Longest running tests
- 25.054 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 6.61 secs - fetch fetch (from Github) - _Mobile Safari_
- 6.476 secs - walkBeta2 can populate type, mode, oid, and content - _Safari_
- 5.743 secs - statusMatrix statusMatrix (pattern vs pattern + filepaths) - _Safari_
- 5.493 secs - fetch shallow fetch (from Github) - _Mobile Safari_
- 5.221 secs - statusMatrix statusMatrix (pattern vs pattern + filepaths) - _Mobile Safari_
- 5.119 secs - fetch fetch --prune from git-http-mock-server - _Mobile Safari_
- 4.205 secs - fetch shallow fetch (from Github) - _Safari_
- 4.144 secs - merge merge 'remove-files' and 'add-files' - _Safari_
- 4.059 secs - fetch shallow fetch relative (from Github) - _Mobile Safari_
- 4.017 secs - status status - _Safari_

**Pull request merged**
