### PR TITLE
fix: don't access process without check

### PR DESCRIPTION
**Pull request by Vinzent03**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

It took me a while to know why my [plugin](https://github.com/Vinzent03/obsidian-git) stopped working on mobile. This https://github.com/isomorphic-git/isomorphic-git/pull/1907/files#diff-3c52af97ec1834ad8729a4d3872436b50140f1bc6fe8e6732d234b7e983d6765R131 introduced the usage of `process` without any check of whether it even exists, since this package should be isomorphic.
I've now added a check to verify `process` exists.

### CODE REVIEW

**Comment by jcubic** [comment]
Are you sure that `trustino` should be true for browser? Can you maybe create some unit test?

**Comment by Vinzent03** [comment]
I'm unsure on how to create the correct unit test. But from reading the code, it should be working like before #1904 by setting `trustino` to true, doesn't it? It's the default value in `compareStats()` as well.

**Comment by jcubic** [comment]
I will check this later. I'm not sure if LightingFS or BrowserFS use Inodes for their FS in status, that's why I was asking this.

**Comment by jcubic** [comment]
I will merge this since it's better than throwing error.

**Comment by jcubic** [comment]
I've checked lightingFS library, and it seems that the ino property in `fs.status` return unique value that identify the file.

**Pull request merged**
