### PR TITLE
fix: fixed crash when shallow cloning certain repositories

### LINKED ISSUE #624: clone fails to complete when cloning certain repositories with depth=1
When clone is called with a depth of 1 on certain repositories, it fails to create the clone and causes the process to terminate early.

Here are two repositories that cause isomorphic-git trouble:

* https://github.com/asciidoctor/asciidoctor.git
* https://github.com/vuejs/vue.git

Execution stops inside the following call in fetchPackfile:

```js
let response = await parseUploadPackResponse(raw);
```

Here's a sample program to reproduce the issue:

```js
const fs = require('fs')
const git = require('isomorphic-git')

;(async () => {
  const url = 'https://github.com/vuejs/vue.git'
  const dir = 'clone.git'
  const repo = { fs, dir, gitdir: dir, url }
  const depth = 1
  await git.clone({ ...repo, depth, noTags: true, noCheckout: true })
  console.log('done')
})()
```

### PR DESCRIPTION
**Pull request by wmhilton**
fixes #624 Issue was through2 stopped reading from packetlines after the highWaterLimit (~16kb)

### CODE REVIEW

**Comment by mojavelinux** [comment]
This definitely seems like the right change. Additionally, perhaps we can figure out how to gracefully handle a server shutdown so at least it doesn't cause the process to terminate if it happens. I think we're just missing the right observer. Surely the HTTP client provides an event for that case, right?

**Comment by karma-pr-reporter** [comment]
## Test Results for 7a920801aee645755bbf0ac8fb4fa5f3aa8d0753:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 224 | 1 | 0 | 1 min 0.417 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 224 | 1 | 0 | 1 min 42.979 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 224 | 1 | 0 | 2 mins 53.894 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 3 mins 43.353 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 224 | 1 | 0 | 4 mins 18.59 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 224 | 1 | 0 | 5 mins 3.586 secs | false | undefined |

**Comment by mojavelinux** [comment]
> Thank you wmhilton!

I second what @isomorphic-git-bot has to say. :trophy:

**Comment by karma-pr-reporter** [comment]
## Test Results for 25e0c7332876ad4effc55f6b6b4ed2d5f9042a17:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 224 | 1 | 0 | 57.205 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 224 | 1 | 0 | 1 min 32.582 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 224 | 1 | 0 | 2 mins 59.111 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 3 mins 44.788 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 224 | 1 | 0 | 3 mins 56.001 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 224 | 1 | 0 | 4 mins 34.588 secs | false | undefined |

**Pull request merged**
