### PR TITLE
Fix extractSection

### PR DESCRIPTION
**Pull request by TomasHubelbauer**
This was failing for me in case of `[core]` where it would return `core]` and not `core` due to `indexOf(' ')` being -1. Here I remove non-matches and only do `min` on actual indices.

### CODE REVIEW

**Comment by wmhilton** [comment]
Awesome! I'll take a look at this - there may be some other edge cases where my config parser is flaky

**Comment by wmhilton** [comment]
Sorry for the delay merging this. I'm trying to set up a linter bot to automatically fix style issues. In this case, some semicolons are blocking the real tests from running. 🙄 I'm all for linters generally speaking, but would prefer they not be friction that discourages pull requests. I'm using "prettier-standard" which *should* just automatically fix everything... but I need to figure out how to run it on PRs instead of relying on contributors to use the pre-push git hooks.

**Comment by wmhilton** [comment]
Ouch. @stickler-ci didn't even introduce himself or say compete sentences. Sigh. Time to build a better bot.

**Comment by TomasHubelbauer** [comment]
I'm okay with adjusting the code to conform to style (although would be good to add a README section on environment setup so contributors don't need to figure this out on their own - I have not used Standard before). But generally I just fixed one issue I had and I didn't test it pretty much at all so it could benefit from your review before merging just to make sure I didn't contribute something incomplete.

**Comment by wmhilton** [comment]
Oh it's really simple to use [prettier-standard](https://npm.im/prettier-standard). There is an nps script "nps format" but that assumes nps is installed globally - I should make an npm script to run it and describe the process in the README.

OR I could make a script that runs "nps format; git add -u; git commit -m 'fix linting errors': git push $pr_branch" and free contributors from having to deal with style/linting altogether.

**Comment by TomasHubelbauer** [comment]
I am not a fan of tooling committing on my behalf (you can pry the capital first letter of a commit message from my cold dead hands, unless of course the contributing guidelines say otherwise :-P). A section on setup is I think 100 % sufficient.

**Comment by TomasHubelbauer** [comment]
NPS looks really neat.

**Comment by wmhilton** [comment]
Eh, so apparently PRs originating from another repository (i.e. https://github.com/TomasHubelbauer/isomorphic-git) can't be added to by the destination repo's owner (except to merge the destination branch into the PR branch via the "Update Branch" button) unless you check a certain checkbox on the right-hand side. https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ So my idea of having a bot auto-append a commit to tidy up PRs won't work.

I'll add something to the README soon but ~~basically:~~ Nevermind, it was not basic. (In hindsight, I'm not sure how anyone is able to code anything at all.) I have composed and tested this complicated-looking recipe that if you run it, should make your PR good to go!

```sh
git clone https://github.com/TomasHubelbauer/isomorphic-git
cd isomorphic-git
git checkout patch-1
git reset --hard 51e86dc
git remote add upstream https://github.com/isomorphic-git/isomorphic-git
git fetch upstream
git rebase upstream/master
npm install
npm run format
git add -u
git commit --amend --no-edit
git push -f
```

Jeepers. I think I'm just going to put in the README "ping me on Twitter and I'll add you as a contributor to the main repo". 😄

**Comment by TomasHubelbauer** [comment]
:-D Awesome, thanks for putting this together!

**Comment by wmhilton** [comment]
Did you get a chance to try updating this PR? Or if that fails, you can open a new PR using the latest master. I could make the change myself in another PR but I didn't want to deny you the credit in the commit history.

**Comment by TomasHubelbauer** [comment]
@wmhilton Let me see if I can squeeze that in today, otherwise feel free to take over it. :-)

**Comment by TomasHubelbauer** [comment]
Closed by #109.

**Pull request closed without merging**
