### PR TITLE
Mshanemc/multi-add-from-1228

### PR DESCRIPTION
**Pull request by mshanemc**
This is a re-work of https://github.com/isomorphic-git/isomorphic-git/pull/1228  (@crutchcorn) to help move things along

## I'm adding a parameter *type* to an existing command add:

- [x] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [x] document the parameter in the JSDoc comment above the function
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

FYI, setup for local testing is `package.json`

``` json
  "type": "commonjs",
```

### CODE REVIEW

**Comment by mshanemc** [comment]
basic summary of where this landed
1. promise.allSettled (can't get polyfill/shim to work) so I moved everything to node12
2. ran into the cjs/esm problems that you know well, so I made changes based on https://github.com/isomorphic-git/isomorphic-git/pull/1436 to get it to build without changing `module` to `commonjs`
3. placated the linters (I think) in one large commit to help tell the changes from the "changes"
4. had to bump some dependencies for tests to find all the modules.  Not sure what that's about.
5. had to set config file on the webpack script to get it to produce the umd in the normal place.

Once all that was done (mostly just banging away on it) I can get this to pass tests locally and in the CI.  🎉

**Comment by mojavelinux** [comment]
> promise.allSettled (can't get polyfill/shim to work) so I moved everything to node12

I would prefer for the move to Node.js 12 to happen in a separate PR. If the maintainers agree with that position, would you be willing to put that together?

**Comment by mojavelinux** [comment]
We could also really use help with #1496. I think that would make the contribution process a lot more straightforward and help eradicate some of these build / CI issues. Would you be willing to help with that?

**Comment by jcubic** [comment]
I'm all in removing support for Node 10, there may be a problem to disable it on Azure. If I will not be able to remove it, maybe we will need to wait for GitHub actions with this.

Another idea is to just merge this as is, and later remove Node 10 when we will migrate to GitHub actions, first we will need access to isomorphic-git NPM repo, we need to be added as contributors. I'm wondering if we can just modify pakcage.json add ourselves as collaborators and on the next deployment will allow us to get NPM credentials or tokens whatever is needed to publish to NPM (I've never done this in CI).

Just thinking at loud will check what is needed for migration to GitHub actions.

**Comment by jcubic** [comment]
@mshanemc it would be also a good idea to remove all prettier fixes from PR or if they actually should be there, then we will need to check why there is no bot for fixing the code anymore.

Actually, it was really nice, because we did not need to worry about style.

**Comment by mshanemc** [comment]
> > promise.allSettled (can't get polyfill/shim to work) so I moved everything to node12
> 
> I would prefer for the move to Node.js 12 to happen in a separate PR. If the maintainers agree with that position, would you be willing to put that together?

I would.  That PR would have to go in ahead of what's left of adding multiple files, which is what we really need to be able to use iso-git

**Comment by mshanemc** [comment]
> We could also really use help with #1496. I think that would make the contribution process a lot more straightforward and help eradicate some of these build / CI issues. Would you be willing to help with that?

It's good to do, but doesn't solve anything I encountered--the nps scripts, module vs. cjs differences between node versions, and eslint/prettier issues are more of a problem than the azure pipelines.

**Comment by mshanemc** [comment]
> I'm all in removing support for Node 10, there may be a problem to disable it on Azure. If I will not be able to remove it, maybe we will need to wait for GitHub actions with this.
This PR changed Azure to run on 12.  That worked fine.

> 
> Another idea is to just merge this as is, and later remove Node 10 when we will migrate to GitHub actions, first we will need access to isomorphic-git NPM repo, we need to be added as contributors. I'm wondering if we can just modify pakcage.json add ourselves as collaborators and on the next deployment will allow us to get NPM credentials or tokens whatever is needed to publish to NPM (I've never done this in CI).
> 
> Just thinking at loud will check what is needed for migration to GitHub actions.

**Comment by mojavelinux** [comment]
> It's good to do, but doesn't solve anything I encountered...

Agreed. I wasn't suggesting that effort as a prerequisite. I was roping you in since you've already gotten into the build process, I think you're well on your way to being able to help us solve it. The Azure pipelines create an incredible amount of confusion since so few people are familiar with them.

**Comment by mojavelinux** [comment]
> I would. That PR would have to go in ahead of what's left of adding multiple files, which is what we really need to be able to use iso-git

I think dropping Node.js 10 needs to go in first. The alternative is to get this build working with Node.js 10. We can't do both in one commit as it makes the upgrade difficult to isolate when studying the history. It's also just not a good practice to couple discrete efforts.

**Comment by mshanemc** [comment]
> @mshanemc it would be also a good idea to remove all prettier fixes from PR or if they actually should be there, then we will need to check why there is no bot for fixing the code anymore.
> 
> Actually, it was really nice, because we did not need to worry about style.

I tried to align the .prettierrc with what the project was doing already (ex: singlequotes instead of prettier's default double, no-semi) based on all the errors it was throwing.

What remained (mostly `function[space](params)`) prettied _just does_ in v2 so it's gonna happen whenever y'all upgrade anyway
https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot

**Comment by mshanemc** [comment]
> > It's good to do, but doesn't solve anything I encountered...
> 
> Agreed. I wasn't suggesting that effort as a prerequisite. I was roping you in since you've already gotten into the build process, I think you're well on your way to being able to help us solve it. The Azure pipelines create an incredible amount of confusion since so few people are familiar with them.

I'd agree to a little OSS volunteer work if my PR(s) go in 😄

**Comment by mshanemc** [comment]
> > I would. That PR would have to go in ahead of what's left of adding multiple files, which is what we really need to be able to use iso-git
> 
> I think dropping Node.js 10 needs to go in first. The alternative is to get this build working with Node.js 10. We can't do both in one commit as it makes the upgrade difficult to isolate when studying the history. It's also just not a good practice to couple discrete efforts.

OK, will make that a separate PR without the multi-add and will see if it's possible to use the older version of prettier and still get past the linter.

**Comment by mojavelinux** [comment]
I'm not sure if this helps, especially since we're talking about dropping Node.js 10 anyway, but just in case...

Here's the polyfill I've used in the past for Promise.allSettled.

```js
Promise.allSettled = (iterable) =>
  Promise.all(
    iterable.map((it) =>
      it.then(
        (value) => ({ status: 'fulfilled', value }),
        (reason) => ({ status: 'rejected', reason })
      )
    )
  )
```

**Comment by mshanemc** [comment]
node12 PR here: https://github.com/isomorphic-git/isomorphic-git/pull/1507
I think I solved the `prettier` issue, too (pointer in package.json its the config file!)

**Comment by mshanemc** [comment]
this PR without the node/build stuff is https://github.com/isomorphic-git/isomorphic-git/pull/1508

**Pull request closed without merging**
