### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by wmhilton** [comment]
I'm a little hesitant to cache the node_modules folder because of [this](https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm)... but also it doesn't seem to have sped it up the install. If anything, 77s is a little higher than average. Oh computers, they vex me!

**Comment by DanielRuf** [comment]
Wait, I have to trigger a new build to actually use the cache ;-)

**Comment by wmhilton** [comment]
Haha, ooh, because I merged @TheLarkInn's PR into master, @renovate[bot] rebased three of its PRs (darn robots are so fast) and so your PR build is now like 5th in line. :( I wish I had more resources. I've throttled Travis to run tests serially because otherwise I run out of concurrent Sauce Labs connections.

**Comment by wmhilton** [comment]
Big win! Adding the cache takes 5-10 seconds but the install goes from 60s to 13s. Awesome!

Since I'm not testing on multiple versions of Node, caching native node modules shouldn't be a problem.

**Pull request merged**
