### PR TITLE
fix: statusMatrix hang (#1768)

### PR DESCRIPTION
**Pull request by coderaiser**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

## I'm adding a parameter to an existing command X:

- [ ] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [ ] document the parameter in the JSDoc comment above the function
- [ ] add a test case in `__tests__/test-X.js` if possible
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

## I'm adding a new command:

- [ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [ ] add command to `src/index.js`
- [ ] update `__tests__/test-exports.js`
- [ ] create a test in `src/__tests__`
- [ ] document the command with a JSDoc comment
- [ ] add page to the Docs Sidebar `website/sidebars.json`
- [ ] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

It is almost all the time is different, so it's never ending loop:
image

### CODE REVIEW

**Comment by coderaiser** [comment]
```sh
    1 ---nano¬
    2 269937500 269937500¬
    3 269937500 269937500¬
    4 ---seconds¬
    5 1685368242 1685368242¬
    6 1685368242 1685368242¬
    7 ---nano¬
    8 870355957.03125 870355957¬
    9 870355957.03125 870355957¬
   10 ---seconds¬
   11 1685356715 1685356715¬
   12 1685356715 1685356715¬
   13 ---nano¬
   14 269937500 269937500¬
   15 269937500 269937500¬
   16 ---seconds¬
   17 1685368242 1685368242¬
   18 1685368242 1685368242¬
   19 ---nano¬
   20 870510498.046875 870510498¬
   21 870510498.046875 870510498¬
```

**Comment by jcubic** [comment]
How about if we include both checks, this will work for both cases, because right now you've broken the tests.

Also can you please create unit tests that breaks and your code fixes the issue?

**Review by jcubic — CHANGES_REQUESTED** [review]
How about if we include both checks, this will work for both cases, because right now you've broken the tests.

Also can you please create unit tests that breaks and your code fixes the issue?

**Comment by coderaiser** [comment]
> Also can you please create unit tests that breaks and your code fixes the issue?
I don't understand what breaks, looks like somewhere is infinite loop

**Comment by jcubic** [comment]
Sorry but I can't merge a PR were you delete the unit test.

**Comment by coderaiser** [comment]
image
OK, you can fix it in any way you like, but would be great to get back normal functionality

**Comment by jcubic** [comment]
Please fix ESLint issue, and I will merge.

**Comment by coderaiser** [comment]
As I see code that uses `compareStats` make code run Infinity count of times, so I add `compareStatsFast`, as I see it run the same count of times as before, and in other places I left old behavior.

**Comment by coderaiser** [comment]
Don't know how to test this, I think it can be mocked and checked that proper version is called, or something liked this.

**Comment by jcubic** [comment]
I would just leave compareStats with new code. I wanted both run at the same time before the original author confirmed that this should be reverted.

Right you just left dead code.

**Comment by coderaiser** [comment]
I just want the bug was fixed ASAP, so any solution is good for me, anyways I don't left dead code, I used `fastCompareStats` in the places that affect freezing, and uncommented test, as you see it is passing, so the wolves are fed and the sheep are safe.

Anyways I have no idea how to test this, as I sad.

**Comment by jcubic** [comment]
The code was reverted, no need for this PR anymore.

**Comment by coderaiser** [comment]
What is wrong with this PR? It fixes code for both case and tests keep passing.

**Comment by jcubic** [comment]
The PR is wrong because it undo the code and I did `git revert` to undo the code that introduced the error.

**Comment by jcubic** [comment]
What is the point of `compareStatsFast` this is like adding a hack to the library to fix your use case. The error that was introduced which this PR attempted to solve was removed by `git revert` so this PR is not needed anymore.

**Pull request closed without merging**
