### PR TITLE
fix: fix type of WalkerMap

### LINKED ISSUE #1313: Is the type of ` WalkerMap` wrong?
Now `type WalkerMap` is 
```ts
export type WalkerMap = (filename: string, entries: WalkerEntry[] | null) => Promise<any>;
```
https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/api/walk.js#L9-L14

https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/typedefs.js#L91-L100

But the item of `entries` can be `null`.
Is correct `(WalkerEntry | null)[]`? ~~If so, I want to create a Pull Request.~~ Created #1314
https://github.com/isomorphic-git/isomorphic-git/blob/89c0da78d5ebf3c9f2754b3c8d557155dd70c8d7/__tests__/test-walk.js#L155-L172

### PR DESCRIPTION
**Pull request by mkizka**
fix #1313 
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by jcubic** [comment]
Hey, can you resolve the conflicts? I'm a new maintainer and will merge the PR if there are no merge issues.

**Comment by mkizka** [comment]
Thanks for your comment. There was a mistake in the commit user, so I am fixing it with force-push. Please wait a little more.

**Comment by mkizka** [comment]
My problem was resolved. It's okay to merge this PR.

**Comment by jcubic** [comment]
Hi, the conflict was not resolved, I've needed to resolve it myself. Thanks for the PR.

**Pull request merged**
