### PR TITLE
chore(ci): see if we can fix bundlesize command

### PR DESCRIPTION
**Pull request by wmhilton**

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for a0bd6057312a68331d0a44a06e47ac5ab2b94863:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 6m:28s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 4m:6s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 1m:52s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:47s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 6m:40s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:46s | false       |

### Longest running tests
- 37.843 secs - fetch fetch (from Github) - _Edge_
- 33.601 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 17.723 secs - fetch shallow fetch relative (from Github) - _Edge_
- 15.041 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 14.525 secs - fetch fetch (from Github) - _Firefox_
- 13.963 secs - fetch shallow fetch (from Github) - _Edge_
- 13.152 secs - fetch shallow fetch (from Github) - _Firefox_
- 11.625 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 11.025 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 9.621 secs - GitPackIndex from .pack - _Firefox_
- 9.396 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for c8371c3cf8532f1cc441970e893d3e5d2fb40f62:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 3m:14s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 5m:13s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 2m:5s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:53s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 3m:46s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:48s | false       |

### Longest running tests
- 33.233 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 23.067 secs - fetch fetch (from Github) - _Firefox_
- 19.136 secs - fetch shallow fetch relative (from Github) - _Edge_
- 18.323 secs - fetch shallow fetch (from Github) - _Firefox_
- 18.068 secs - GitPackIndex to .idx file from .pack - _Edge_
- 16.762 secs - GitPackIndex from .pack - _Edge_
- 14.894 secs - fetch shallow fetch (from Github) - _Edge_
- 14.275 secs - fetch fetch (from Github) - _Edge_
- 14.017 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 11.743 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 10.244 secs - fetch shallow fetch relative (from Github) - _Firefox_

**Comment by karma-pr-reporter** [comment]
## Test Results for 42a19666f11b53fa1dfb5ba2d5f06ce71c4e3143:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 309  | 1    | 3    | 3m:15s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 5m:10s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 1m:52s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:48s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 198  | 2    | 0    | 3m:12s | true        |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 311  | 1    | 1    | 3m:46s | false       |

### Erroring Tests

- Safari 11.1.2 (Mac OS X 10.13.6):
  - merge merge two branches that modified the same file (no conflict)'
- Chrome Mobile 69.0.3497 (Android 7.1.1):
  - push push to Github using token
  - push push with Basic Auth
  - push throws an Error if invalid credentials supplied

### Longest running tests
- 34.725 secs - fetch fetch (from Github) - _Edge_
- 31.348 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 26.939 secs - fetch shallow fetch (from Github) - _Edge_
- 15.393 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 14.677 secs - fetch shallow fetch relative (from Github) - _Edge_
- 12.29 secs - fetch fetch (from Github) - _Firefox_
- 12.211 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 10.852 secs - GitPackIndex from .pack - _Firefox_
- 10.707 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 9.805 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 9.778 secs - fetch shallow fetch exclude (from Github) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 42a19666f11b53fa1dfb5ba2d5f06ce71c4e3143:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 2m:58s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 3m:41s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:40s | false       |

### Longest running tests
- 25.114 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 10.52 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 8.707 secs - fetch fetch (from Github) - _Chrome Mobile_
- 6.251 secs - fetch shallow fetch (from Github) - _Chrome Mobile_
- 5.868 secs - statusMatrix statusMatrix (pattern vs pattern + filepaths) - _Safari_
- 4.707 secs - fetch shallow fetch relative (from Github) - _Chrome Mobile_
- 4.369 secs - walkBeta2 can populate type, mode, oid, and content - _Chrome Mobile_
- 4.261 secs - statusMatrix statusMatrix (pattern vs filepaths) - _Mobile Safari_
- 4.198 secs - merge merge 'add-files' and 'remove-files' - _Safari_
- 4.143 secs - statusMatrix statusMatrix (pattern vs filepaths) - _Chrome Mobile_
- 4.126 secs - walkBeta2 can populate type, mode, oid, and content - _Safari_

**Comment by wmhilton** [comment]
its getting worse

**Comment by karma-pr-reporter** [comment]
## Test Results for c1d3fc403c819491c1a47f01a6afc287dfa6c393:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 312  | 1    | 0    | 3m:39s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 312  | 1    | 0    | 5m:5s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 312  | 1    | 0    | 1m:51s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 312  | 1    | 0    | 0m:46s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 311  | 2    | 0    | 3m:42s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 312  | 1    | 0    | 3m:48s | false       |

### Longest running tests
- 34.294 secs - fetch fetch (from Github) - _Edge_
- 30.237 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 17.704 secs - fetch fetch (from Github) - _Firefox_
- 16.741 secs - fetch shallow fetch (from Github) - _Edge_
- 14.08 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 14.078 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 13.741 secs - fetch shallow fetch since (from Github) - _Edge_
- 12.66 secs - fetch shallow fetch relative (from Github) - _Edge_
- 12.645 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 10.569 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 9.298 secs - fetch shallow fetch exclude (from Github) - _Firefox_

**Pull request closed without merging**
