### PR TITLE
Add noSubmodules to pull as well

### PR DESCRIPTION
**Pull request by TomasHubelbauer**
## I'm adding a parameter to an existing command:

- [x] add parameter to the function in `src/commands/X.js`
- [x] document the parameter in the JSDoc comment above the function
- [x] add parameter to the TypeScript library definition for X in `src/index.d.ts`
- [ ] add a test case in `__tests__/test-X.js` if possible
- [ ] squash merge the PR with commit message "feat: Added 'bar' parameter to X command"

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
This is another fix for #943

**Comment by karma-pr-reporter** [comment]
## Test Results for 9180de3acc3b45350c15f9275df91dd24aa48b0d:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 329  | 1    | 0    | 2m:11s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 329  | 1    | 0    | 5m:2s  | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 329  | 1    | 0    | 1m:52s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 329  | 1    | 0    | 0m:50s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 328  | 2    | 0    | 2m:22s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 329  | 1    | 0    | 3m:40s | false       |

### Longest running tests
- 27.004 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 20.001 secs - fetch fetch (from Github) - _Firefox_
- 19.456 secs - GitPackIndex from .pack - _Edge_
- 18.41 secs - fetch fetch (from Github) - _Edge_
- 17.926 secs - GitPackIndex to .idx file from .pack - _Edge_
- 17.796 secs - fetch shallow fetch relative (from Github) - _Edge_
- 12.046 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 11.741 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 11.73 secs - fetch shallow fetch since (from Github) - _Edge_
- 11.677 secs - GitPackIndex from .pack - _Firefox_
- 11.586 secs - fetch shallow fetch using autoTranslateSSH param (from Github) - _Edge_

**Comment by wmhilton** [comment]
Thanks for your patience!

**Comment by TomasHubelbauer** [comment]
Verified working.

**Pull request merged**
