### PR TITLE
chore: switch from BrowserFS to lightning-fs backend

### PR DESCRIPTION
**Pull request by wmhilton**

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for e1bdf04aefc533d57389880963424cfcc19ef273:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 23.101 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 1.972 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 4 mins 33.111 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 4 mins 51.382 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 49 | 1 | 0 | 7 mins 1.733 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e1bdf04aefc533d57389880963424cfcc19ef273:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|

**Comment by karma-pr-reporter** [comment]
## Test Results for e1bdf04aefc533d57389880963424cfcc19ef273:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0 | 0 | 0 | 6 mins 14.816 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 39c19860b620c241a152ca7bf0164d787efe529d:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 20.636 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 19.47 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 3 mins 27.276 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 5 mins 45.444 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 5 mins 56.572 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for b5e45d87107c96e393fe0607663e224512b6b0b4:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 47.698 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 40.364 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 4 mins 26.687 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 7 mins 8.302 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 50 | 0 | 0 | 8 mins 0.727 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for b5e45d87107c96e393fe0607663e224512b6b0b4:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 194 | 1 | 5 | 13 mins 55.688 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for b5e45d87107c96e393fe0607663e224512b6b0b4:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0 | 0 | 0 | 9 mins 39.28 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 88d3df86dc5cc25e2c8671fb8fedce9e86aec75c:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 46.543 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 32.652 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 4 mins 31.625 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 242 | 1 | 1 | 6 mins 32.2 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0 | 0 | 0 | 7 mins 34.695 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 88d3df86dc5cc25e2c8671fb8fedce9e86aec75c:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 6 mins 1.863 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 150 | 0 | 0 | 9 mins 5.19 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 88d3df86dc5cc25e2c8671fb8fedce9e86aec75c:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 97 | 0 | 3 | 9 mins 58.981 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 45ab3773e9e7174bd2a457a1a1669fe22dec0ee7:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 52.909 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 35.438 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 4 mins 33.968 secs | false | undefined |
| Mobile Safari 12.0.0 (iOS 12.0.0) | 243 | 1 | 0 | 5 mins 57.46 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 6 mins 35.549 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 1409b1035b42ae591b8bcafe96de94693b9e211e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 43.531 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 36.425 secs | false | undefined |
| Mobile Safari 12.0.0 (iOS 12.0.0) | 122 | 1 | 121 | 2 mins 53.352 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 5 mins 39.11 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 6 mins 45.461 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 7 mins 29.397 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 1409b1035b42ae591b8bcafe96de94693b9e211e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 12.0.0 (iOS 12.0.0) | 140 | 1 | 103 | 4 mins 7.261 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 1409b1035b42ae591b8bcafe96de94693b9e211e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 12.0.0 (iOS 12.0.0) | 0 | 0 | 0 | 6 mins 39.543 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 1409b1035b42ae591b8bcafe96de94693b9e211e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 12.0.0 (iOS 12.0.0) | 158 | 1 | 85 | 3 mins 39.303 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 5 mins 57.546 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 7 mins 54.514 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 1409b1035b42ae591b8bcafe96de94693b9e211e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 12.0.0 (iOS 12.0.0) | 243 | 1 | 0 | 6 mins 36.125 secs | false | undefined |

**Comment by wmhilton** [comment]
Hmm. Finally passed... but I'm gonna vote that even on Safari 12, LightningFS is... unstable.

**Comment by karma-pr-reporter** [comment]
## Test Results for c87783f8a51f01c96bfe5729c54a894af1255f2b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 25.827 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 26.086 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 6 mins 2.957 secs | false | undefined |

**Comment by wmhilton** [comment]
We'll just try this again after Christmas. I have a feeling Sauce Labs's Safari stuff is just broke right now.
image

**Comment by karma-pr-reporter** [comment]
## Test Results for c87783f8a51f01c96bfe5729c54a894af1255f2b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 3 mins 3.033 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 4 mins 45.206 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for c87783f8a51f01c96bfe5729c54a894af1255f2b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|

**Comment by karma-pr-reporter** [comment]
## Test Results for c87783f8a51f01c96bfe5729c54a894af1255f2b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 18.17763.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 1 min 21.905 secs | true | undefined |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 31.31 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 40.204 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 3 mins 46.867 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 5 mins 10.801 secs | false | undefined |

**Comment by wmhilton** [comment]
I think I've figured it out. Every Safari run on Sauce has failed since the tests started running on Mojave.

**Comment by karma-pr-reporter** [comment]
## Test Results for a410d08462a3ee1d364e1402aa43f755e8b93a37:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 17.728 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 32.996 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 243 | 1 | 0 | 3 mins 5.914 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 3 mins 57.003 secs | false | undefined |
| Edge 18.17763.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 5 mins 4.419 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 5 mins 14.801 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for f97cd9c4d72acca4fe02f063baff2ea37626cd22:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 243 | 1 | 0 | 1 min 23.676 secs | false | undefined |
| Firefox 64.0.0 (Ubuntu 0.0.0) | 243 | 1 | 0 | 2 mins 34.539 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 243 | 1 | 0 | 3 mins 40.279 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 0 | 4 mins 2.557 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 243 | 1 | 0 | 4 mins 51.123 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 243 | 1 | 0 | 5 mins 47.684 secs | false | undefined |

**Comment by wmhilton** [comment]
Ship it!

**Pull request merged**
