### PR TITLE
This addresses changes to auth API #1722

### PR DESCRIPTION
**Pull request by konsumer**
I removed all the header stuff (since it's not in the `push` function anymore) and added notes on adding it to the URL or using `onAuth`

Related: #1722

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm good with this change. The permutations of oauth options are already covered on the onAuth page and is thus redundant here. So I believe it is wise to remove that matrix, which is difficult to maintain anyway.

Given what was on this page, I honestly think it had just been forgotten about. The shorter we can make it, the better.

**Comment by konsumer** [comment]
Yeh, I removed the matrix because these are no longer options to `push`, as shown in the example. I tried to show quickly "this works for gitlab/github/bitbucket, and you can also ask user/filesystem on fail with `onAuth`" (which I linked to.) It may be less complete/thorough than it was before, but now it's all working examples.

Hopefully that helps.

**Comment by mojavelinux** [comment]
Yep, we're on the same page.

**Comment by jcubic** [comment]
OK if @mojavelinux thinks this it good. I will merge it.

**Comment by jcubic** [comment]
Hi, I think that you edited the wrong file. Your changes are not public the file on the website is located at:

https://github.com/isomorphic-git/isomorphic-git.github.io/edit/source/docs/authentication.md

Which you can see if you click the edit button on:

https://isomorphic-git.org/docs/en/authentication

I'm not sure what is the purpose of the file you've edited.

**Comment by jmarks-joshua** [comment]
Yeah this is still an issue. Also didn't github disable basic https password authentication in August 2021?

So even without 2fa you cannot just use your email address and password and need to use 'personal access tokens', but then they should have an expiry so need to keep them up-to-date somehow.

**Pull request merged**
