### PR TITLE
feat: Added 'force' parameter to branch command to overwrite existing branch

### LINKED ISSUE #639: Add flag to force branch creation
The use case I'm trying to address is to either create a branch and switch to it or just switch to it if it already exists. It's the functional equivalent of:

```js
await git.branch({ ...repo, ref: 'branchname', checkout: true })
  .catch((e) => {
    if (e.code === git.E.RefExistsError && e.data.noun === 'branch') {
      return git.checkout({ ...repo, ref: 'branchname' })
    }
    throw e
  })
```

However, that's not idiomatic. It also requires some work to avoid calling checkout with side effects (the creation of a remote tracking branch).

What I'd like to be able to do is force create the branch:

```js
await git.branch({ ...repo, ref: 'branchname', force: true })
```

which is the same as `git branch -f branchname`.

which I can then combine with the checkout option to checkout the branch at the same time:

```js
await git.branch({ ...repo, ref: 'branchname', checkout: true, force: true })
```

which is the same as `git checkout -B branchname`.

The `force` flag would thus allow isomorphic-git to cover both use cases.

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #639

## I'm adding a parameter to an existing command:

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] add parameter to the function in `src/commands/X.js`
- [ ] add parameter to [docs](https://github.com/isomorphic-git/isomorphic-git.github.io/tree/source/docs)/X.md
- [x] add parameter to the TypeScript library definition for X in `src/index.d.ts`
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] squash merge the PR with commit message "feat: Added 'bar' parameter to X command"

### CODE REVIEW

**Comment by mojavelinux** [comment]
The only thing I'm slightly uncomfortable about is that there isn't a test to verify that force updates the oid of an existing branch to match the oid of the current HEAD. However, that would require recreating the test-branch.git repo. Should I do that?

**Comment by karma-pr-reporter** [comment]
## Test Results for d920d2355a948f921bf2713bbeb8f5941c2823cb:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 244 | 1 | 0 | 57.866 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 244 | 1 | 0 | 1 min 33.868 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 244 | 1 | 0 | 2 mins 42.91 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 244 | 1 | 0 | 3 mins 1.207 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 244 | 1 | 0 | 3 mins 46.665 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 244 | 1 | 0 | 4 mins 33.084 secs | false | undefined |

**Comment by wmhilton** [comment]
Yes, we should add an assertion to check that `force` updates the oid the branch points to.

**Comment by mojavelinux** [comment]
Tests are update. The test now verifies that force will abandon the oid of the existing branch and reset it to the one from HEAD.

**Comment by karma-pr-reporter** [comment]
## Test Results for 2cd32dc34e1fed37612e4dfb162685659df1ffd6:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 244 | 1 | 0 | 1 min 14.266 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 244 | 1 | 0 | 2 mins 16.148 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 244 | 1 | 0 | 4 mins 55.19 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 244 | 1 | 0 | 5 mins 30.983 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 243 | 1 | 1 | 7 mins 28.364 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0 | 0 | 0 | 7 mins 46.717 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 2cd32dc34e1fed37612e4dfb162685659df1ffd6:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 244 | 1 | 0 | 3 mins 8.028 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 244 | 1 | 0 | 4 mins 36.179 secs | false | undefined |

**Comment by mojavelinux** [comment]
What's left to do?

**Comment by wmhilton** [comment]
Mostly, I want to make sure we're solving the right problem! See #639. But also I just haven't had a chance to review it yet.

**Pull request closed without merging**
