### PR TITLE
fix: Fix obsolete type information in index.d.ts

### PR DESCRIPTION
**Pull request by raon0211**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

I have found some obsolete type information in the type declaration file as follows:

1. The first argument to `walkBeta2`'s `map` should be `fullpath` (`string`), not `WalkerEntry2[]`. 
   - The correct signature of the `map` function is `(fullpath: string, entries: WalkerEntry2[]) => Promise<T | undefined>`.
2. The `fs` option is no longer required. It has to be optional, but `TREE`, `WORKDIR`, and `STAGE` still requires the option.
3. `WalkerEntry2`'s `content` method should return either `Buffer` or `undefined`, not `Buffer` or `void`. (Note that `void` in TypeScript dictates that the return value cannot be used in any way.)

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser                            | Pass | Skip | Fail | Time   | Disconnect? |
| ---------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Edge 17.17134.0 (Windows 10 0.0.0) | 382  | 1    | 0    | 4m:30s | false       |
| Firefox 72.0.0 (Ubuntu 0.0.0)      | 382  | 1    | 0    | 1m:44s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 382  | 1    | 0    | 0m:51s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)  | 381  | 2    | 0    | 3m:5s  | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)   | 382  | 1    | 0    | 3m:43s | false       |

### Longest running tests
- 24.773 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 21.809 secs - fetch fetch (from Github) - _Firefox_
- 19.104 secs - GitPackIndex from .pack - _Edge_
- 18.989 secs - fetch shallow fetch relative (from Github) - _Edge_
- 17.612 secs - GitPackIndex to .idx file from .pack - _Edge_
- 13.879 secs - fetch shallow fetch (from Github) - _Edge_
- 13.365 secs - fetch fetch (from Github) - _Edge_
- 13.331 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 11.583 secs - GitPackIndex from .pack - _Firefox_
- 11.231 secs - fetch shallow fetch since (from Github) - _Edge_
- 10.781 secs - fetch fetch (from Github) - _Mobile Safari_

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by wmhilton** [comment]
Thanks! Yes, keeping the TypeScript declaration for in sync with the code in sync with the docs has been a real issue with 0.x.x. I'm completely rewriting the types for 1.x.x to take advantage of the fact TS 3.7 can now emit declaration files for regular JS code using JSDoc!

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser                            | Pass | Skip | Fail | Time   | Disconnect? |
| ---------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Edge 17.17134.0 (Windows 10 0.0.0) | 382  | 1    | 0    | 5m:18s | false       |
| Firefox 72.0.0 (Ubuntu 0.0.0)      | 382  | 1    | 0    | 1m:49s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 382  | 1    | 0    | 0m:53s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)  | 381  | 2    | 0    | 3m:34s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)   | 382  | 1    | 0    | 4m:6s  | false       |

### Longest running tests
- 34.378 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 21.442 secs - fetch shallow fetch relative (from Github) - _Edge_
- 19.196 secs - GitPackIndex from .pack - _Edge_
- 18.121 secs - fetch fetch (from Github) - _Edge_
- 17.976 secs - GitPackIndex to .idx file from .pack - _Edge_
- 17.05 secs - fetch shallow fetch (from Github) - _Edge_
- 14.12 secs - fetch fetch (from Github) - _Firefox_
- 14.075 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 12.323 secs - GitPackIndex from .pack - _Firefox_
- 12.321 secs - GitPackIndex to .idx file from .pack - _Mobile Safari_
- 12.198 secs - GitPackIndex from .pack - _Mobile Safari_

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 0837678e75dcc398044847ddacba653e22ed0790:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by wmhilton** [comment]
Hmm. For some reason the Android tests aren't running. :( I'm going to just bypass the CI restriction for now.

**Pull request merged**
