### PR TITLE
fix: optimize abbreviate in 'currentBranch'

### PR DESCRIPTION
**Pull request by mojavelinux**
only execute a single regular expression to clean the refname

## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by mojavelinux** [comment]
If we didn't have to cut /HEAD off the end of a remote reference, we could do it in a single String#replace call, which would be even faster.

**Comment by mojavelinux** [comment]
This is more than twice as fast.

**Comment by mojavelinux** [comment]
I should also add that it is more correct as well since we now check for `refs/` at the beginning of the string (and not just anywhere in the string).

**Comment by karma-pr-reporter** [comment]
## Test Results for 0aa18791e914328a4441ac44083bf12ee618fde1:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 225 | 1 | 0 | 58.306 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 225 | 1 | 0 | 1 min 35.156 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 225 | 1 | 0 | 2 mins 55.681 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 225 | 1 | 0 | 3 mins 6.664 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 225 | 1 | 0 | 3 mins 47.536 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 225 | 1 | 0 | 4 mins 27.232 secs | false | undefined |

**Comment by wmhilton** [comment]
Not to stomp on your parade, but before we go obfuscating things into ugly regexes that are hard to debug, do you have any evidence that this is actually a hot path that needs to be optimized? Does this change lead to a perceivable benefits in Antora's speed? I mean, how many times a second are you calling `currentBranch`?

**Comment by mojavelinux** [comment]
Stomping is what a parade is all about, so stomp away!

But point taken. To answer you as honestly as possible, this would not impact performance in Antora. It could perhaps come into play in a tight loop that sets up a test fixture. But I agree it's rare.

I still think multiple regular expressions makes the code needlessly verbose. I could back off a bit and make the regular expression easier to read. It also address the important issue of pinning it to the start of the string so we know we're matching the right thing.

I'll propose an update and you can give it another stomp.

**Comment by mojavelinux** [comment]
See if you like that better. I think it's pretty readable now.

**Comment by karma-pr-reporter** [comment]
## Test Results for 474dbc14f6ebf2d734d2a2eb380cf9bbfc07c1dd:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 225 | 1 | 0 | 59.077 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 225 | 1 | 0 | 1 min 32.431 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 225 | 1 | 0 | 3 mins 1.228 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 225 | 1 | 0 | 4 mins 5.199 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 225 | 1 | 0 | 4 mins 11.956 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 225 | 1 | 0 | 9 mins 43.849 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for afdae0b784d88841a225397369ab6b096a647f94:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 226 | 1 | 0 | 57.468 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 226 | 1 | 0 | 1 min 34.081 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 226 | 1 | 0 | 3 mins 15.983 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 226 | 1 | 0 | 3 mins 22.581 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 226 | 1 | 0 | 4 mins 25.051 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 226 | 1 | 0 | 10 mins 28.938 secs | false | undefined |

**Comment by mojavelinux** [comment]
I'm super glad we found something that pleases us both. :clap:

**Pull request merged**
