### PR TITLE
ci: Add GitHub Workflow

### PR DESCRIPTION
**Pull request by seanpoulter**
### Proposed Changes

This PR helps migrate to use GitHub Actions. Here's a summary from #1496:

- [x] Add a GitHub Workflow
- [x] Figure out how the website is updated (It is part of **azure-pipelines.yml**)
- [x] Test Node.js versions ([Release Schedule](https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule))
    - [x] 12 (current)
    - [x] 18 (maintenance)
    - [x] v20 (LTS)
- [x] Change the minimum supported version of Node.js from 12 to 16
- [ ] Modernize the build process

This PR:

- Adds a GitHub Workflow for CI/CD using Node 16
- Adds **.nvmrc** to track the minimum version of Node.js
- Removes the code to tweet on release
- Disables the steps to release and update the website from the Azure DevOps pipeline
- Configures the build/test to work with Webpack v4 and Node.js >= 17

### TODO

* We must set up the secrets
  - [x] `BROWSER_STACK_ACCESS_KEY`
  - [x] `BROWSER_STACK_USERNAME`
  - [x] `BUNDLEWATCH_GITHUB_TOKEN`
  - [x] `GITHUB_TOKEN` (automatic)
  - [x] `NPM_TOKEN`
  - [x] `SAUCE_ACCESS_KEY`
  - [x] `SAUCE_USERNAME`
  - [x] `TWITTER_ACCESS_TOKEN_SECRET` (deleted)
  - [x] `TWITTER_CONSUMER_SECRET` (deleted)

### CODE REVIEW

**Comment by seanpoulter** [comment]
More changes to come:

* Follow [these docs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures) to allow the build to `continue-on-error` for Node.js v18.
* Fix the build for Node.js v18. This is expected with Webpack v4 and won't be fixed.
  https://github.com/webpack/webpack/issues/14532#issuecomment-947513562

**Comment by seanpoulter** [comment]
If we keep the pipeline configured to run for the maintenance and current LTS versions, we probably don't need to retry the Jest tests 3 times in CI.

**Comment by jcubic** [comment]
I'm not sure if we will be able to get all required tokens without the help from original author. Last time I tried to contact him, he didn't reply. I think will try again on LinkedIn since I get the best output from contacting him there.

**Comment by jcubic** [comment]
What permission are required for NPM token? It's for Publish?

**Comment by jcubic** [comment]
Just added NPM token.

I think that `GITHUB_TOKEN` is added automatically by GitHub to be used in GH actions.

**Comment by jcubic** [comment]
Also added Sauce Labs access token and my username, I'm in isomorphic-git or let's hope it will work.

**Comment by seanpoulter** [comment]
> I'm not sure if we will be able to get all required tokens without the help from original author.

We could also try to exfiltrate them from the pipeline. Let me know if/when you want me to try.

**Comment by jcubic** [comment]
I don't thin you can, they are saved in Azure as secrets, and they are written with asterisks.

Przechwycenie obrazu ekranu_2024-03-10_10-45-44

**Comment by seanpoulter** [comment]
We can't access the secrets from the UI but you can use them in the pipeline and run whatever code we want. Here's an [article](https://www.devjev.nl/posts/2022/i-am-in-your-pipeline-reading-all-your-secrets/#retrieving-secret-values) for inspiration which prints them out with base64 encoding.

We could use the GitHub API to create secrets in the repo/org if we had a GitHub token with the right scope and permissions.

* Use the GitHub API to read the org/repo public key required to encrypt the secret
* Encrypt the secret
* Use the GitHub API to create the org/repo secret by name/encrypted value

I'd be surprised if we have the right permissions with the GitHub token used in ADO but we can try. Are we creating the secrets in GitHub for the repo or the organization? It changes the API and token scope we need. :grin:

**Comment by jcubic** [comment]
If that worked, it would be great. But let's wait few days (especially during week day) until we will see if original author will respond on LinkedIn.

> Are we creating the secrets in GitHub for the repo or the organization?

I've created secrets in repo, I have no idea what permission the token have.

**Comment by seanpoulter** [comment]
> Got reply from Billie Hilton on LinkedIN, he said that he will provide the required credentials.

That's great! Thanks Billie! I hope you're well! :wave:

**Comment by jcubic** [comment]
I've merged the PR with disabled test. It seems there is a conflict with that file you modified there.

**Comment by seanpoulter** [comment]
> I've merged the PR with disabled test. It seems there is a conflict with that file you modified there.

I fixed the conflict and rebased. If we get the secrets in I'd expect the Workflows to pass.

**Comment by jcubic** [comment]
Generated my own token and save it to `BUNDLEWATCH_GITHUB_TOKEN`.
I have access to Twitter account, but I think that you can't use their API for free anymore.

**Comment by jcubic** [comment]
Yes, I think so, but first I will check if there are no other way to post to Twitter.

**Comment by jcubic** [comment]
So I got invitation to BrowserStack account, but they don't have something like teams or orgs like in GitHub and got a warning that I need to delete my old account (I already have Open Source account for my other project). I talk with BrowserStack support just now, and it seems that I don't need to delete my account I can use my current one since only TOKEN is needed on BrowserStack part, and it will just work.

I will generate a token soon.

**Comment by jcubic** [comment]
Add BrowserStack, the Twitter can be removed.

**Comment by jcubic** [comment]
What else is needed?

**Comment by seanpoulter** [comment]
> Note that you can't create a secret that start with `GITHUB_`

Ah, sorry, the GITHUB_TOKEN is automatic. I should have checked that off.
Here's the docs - https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

**Comment by seanpoulter** [comment]
> What else is needed?

It's been a while so I've rebased and run the tests. It looks like I've got trouble accessing the Secrets from the Workflow:

* Based on [line 146](https://github.com/isomorphic-git/isomorphic-git/actions/runs/8578244482/job/23511859523?pr=1879#step:5:146) it looks like the Workflow doesn't have access to the `BUNDLEWATCH_GITHUB_TOKEN` secret.
* Based on [line 297](https://github.com/isomorphic-git/isomorphic-git/actions/runs/8578244482/job/23511859523?pr=1879#step:5:297) it looks like the Workflow doesn't have access to the `SAUCE_USERNAME` secret.
* Based on [line 339-341](https://github.com/isomorphic-git/isomorphic-git/actions/runs/8578244482/job/23511859523?pr=1879#step:5:339) it looks like the Workflow doesn't have access to the `BROWSERSTACK_USERNAME` or `BROWSERSTACK_ACCESS_KEY` secrets

**Comment by seanpoulter** [comment]
Based on these errors from Node v18 and v20, we also have to configure NODE_OPTIONS
https://github.com/isomorphic-git/isomorphic-git/actions/runs/8578378966/job/23512154927?pr=1879#step:5:298

**Comment by jcubic** [comment]
I think you can set some kind of permissions inside the workflow file. Maybe this is a problem. We can ask on GitHub Community forum about this issue. The secrets are there.

**Comment by seanpoulter** [comment]
OK. Great! Thanks for confirming they're Repository Secrets.

It turns out it is expected behaviour. Sorry. I'm not used to setting up Workflows in a fork. :facepalm: From [Using secrets in a Workflow](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow):

> With the exception of `GITHUB_TOKEN`, secrets are not passed to the runner when a workflow is triggered from a forked repository.

I'll do a bit more research to confirm how to set this up to run from a fork. I wonder if you reran what it'd do.

**Comment by seanpoulter** [comment]
This is a pretty good reference - https://dvc.ai/blog/testing-external-contributions-using-github-actions-secrets.

**Comment by jcubic** [comment]
I can create experimental branch `workflow` and you create PR to that branch.

**Comment by jcubic** [comment]
Sorry for the late reply, I totally forget that I need to do something. Created a `workflow` branch and I will merge without squash. You can create next PR against that branch.

**Comment by jcubic** [comment]
Created a PR https://github.com/isomorphic-git/isomorphic-git/pull/1901 with your changes. If you have any updates just create a PR to `workflow` branch and I will merge.

**Pull request merged**
