### PR TITLE
fix: pass wrapped fs to GitIgnoreManager.isIgnored (#1076)

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by stefan-guggisberg** [comment]
fixes #1076

**Comment by karma-pr-reporter** [comment]
## Test Results for b73cf4685d6910665e04a3345da7229d38f9f0e7:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome 79.0.3945 (Windows 10 0.0.0)     | 363  | 0    | 0    | 2m:22s | false       |
| Chrome Mobile 78.0.3904 (Android 0.0.0) | 363  | 0    | 0    | 1m:43s | false       |
| Firefox 73.0.0 (Ubuntu 0.0.0)           | 363  | 0    | 0    | 0m:54s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 363  | 0    | 0    | 0m:43s | false       |
| Mobile Safari 13.0.0 (iOS 13.0.0)       | 363  | 0    | 0    | 2m:41s | false       |
| Safari 13.0.3 (Mac OS X 10.15.1)        | 363  | 0    | 0    | 3m:28s | false       |

### Longest running tests
- 10.178 secs - clone clone with noTags - _Chrome_
- 8.31 secs - clone clone with noTags - _Mobile Safari_
- 7.549 secs - clone clone with noTags - _Safari_
- 7.385 secs - clone clone with noTags - _Firefox_
- 7.13 secs - fetch fetch --prune from git-http-mock-server - _Safari_
- 6.874 secs - fetch fetch --prune-tags from git-http-mock-server - _Mobile Safari_
- 6.384 secs - clone clone with noTags - _HeadlessChrome_
- 6.058 secs - statusMatrix statusMatrix with filter - _Safari_
- 5.766 secs - walk can populate type, mode, oid, and content - _Safari_
- 5.719 secs - clone clone with noTags - _Chrome Mobile_
- 5.358 secs - walk can populate type, mode, oid, and content - _Mobile Safari_

**Comment by stefan-guggisberg** [comment]
@wmhilton Can you take a look please? #1076 is a blocker for us and this PR is IMO pretty low risk. Thanks!

**Comment by crutchcorn** [comment]
Thank you so much for fixing this, this is also a blocker for my application

**Comment by wmhilton** [comment]
Doh! I'm sorry 😔. Thank you so much!!

**Comment by crutchcorn** [comment]
Thanks for taking a look at this so quickly @wmhilton! Would you be able to ping this pull request when this is finalized in a release?

**Comment by stefan-guggisberg** [comment]
@wmhilton Thanks!

**Pull request merged**
