### PR TITLE
chore: cache node_modules folder in CI

### PR DESCRIPTION
**Pull request by wmhilton**
try this thing https://medium.com/microsoft-1es/reducing-vs-code-ci-build-times-e0c5872bfdde

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 0c72a6bef3ec1a4a4005ac12bba17778894971d5:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 254 | 1 | 0 | 1 min 23.014 secs | false | undefined |
| Firefox 65.0.0 (Ubuntu 0.0.0) | 254 | 1 | 0 | 2 mins 37.991 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 254 | 1 | 0 | 3 mins 21.099 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 254 | 1 | 0 | 4 mins 3.305 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 254 | 1 | 0 | 4 mins 5.939 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 254 | 1 | 0 | 5 mins 8.624 secs | false | undefined |

**Comment by wmhilton** [comment]
All right! It cuts the dependency install time from 1:05 to 0:32. I wonder which (Azure Artifact or npm) is more resilient / has higher uptime?

**Comment by wmhilton** [comment]
Let's see how much time the Post-job adds though before we get too excited.

**Comment by karma-pr-reporter** [comment]
## Test Results for 34d49d76135a0f4df69d5606f25969f5109ed01a:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 254 | 1 | 0 | 1 min 21.528 secs | false | undefined |
| Firefox 65.0.0 (Ubuntu 0.0.0) | 254 | 1 | 0 | 2 mins 37.233 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 254 | 1 | 0 | 3 mins 43.979 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 254 | 1 | 0 | 3 mins 46.049 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 254 | 1 | 0 | 5 mins 21.83 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 254 | 1 | 0 | 6 mins 12.14 secs | false | undefined |

**Comment by wmhilton** [comment]
Oh heck yeah. the Post-Job ran in 2s. So literally just 30 seconds of savings pretty much all around. Seems like a win!

**Comment by wmhilton** [comment]
cross-referencing https://github.com/Microsoft/azure-pipelines-artifact-caching-tasks/issues/6

**Pull request merged**
