### PR TITLE
feat: support 'pgp' plugin

### PR DESCRIPTION
**Pull request by wmhilton**
## I'm adding a parameter to an existing command:

- [x] add parameter to the function in `src/commands/X.js`
- [ ] add parameter to [docs](https://github.com/isomorphic-git/isomorphic-git.github.io/tree/source/docs)/X.md
- [x] add parameter to the TypeScript library definition for X in `src/index.d.ts`
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] make a feature commit "feat: Added 'bar' parameter to X command"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 64bd745a8cf0cf6411b57c2d8dd886a6759dc89a:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 1 min 5.846 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 41.777 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 3 mins 6.942 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 10.051 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 222 | 1 | 0 | 4 mins 9.556 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 4 mins 42.753 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 2.735 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 2.755 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 215 | 1 | 1 | 4 mins 11.923 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 2.735 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 2.755 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 215 | 1 | 1 | 4 mins 11.923 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 215 | 1 | 1 | 4 mins 11.955 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 40.589 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 40.605 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 9.634 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 9.657 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 40.589 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 40.605 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 9.634 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 50.668 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 50.684 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.145 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e017144141db1d61ad2f98d801b7265ddba70cb8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 50.668 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 50.684 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.145 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.177 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8937bbb013fd6b860ce0df68eb09ad6b516f8d08:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 2 | 51.377 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 2 | 1 min 3.763 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 2 | 2 mins 4.19 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 2 | 3 mins 9.706 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 167 | 0 | 0 | 4 mins 2.068 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 167 | 0 | 0 | 4 mins 2.08 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.436 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.459 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8937bbb013fd6b860ce0df68eb09ad6b516f8d08:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 2 | 51.377 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 2 | 1 min 3.763 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 2 | 2 mins 4.19 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 2 | 3 mins 9.706 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 167 | 0 | 0 | 4 mins 2.068 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 167 | 0 | 0 | 4 mins 2.08 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 7.436 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 58.962 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 37.235 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 29.376 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 8.239 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.309 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.325 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 27.01 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 27.039 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 58.962 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 37.235 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 29.376 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 8.239 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.309 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.325 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 27.01 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 30.94 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 30.958 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 35.544 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 30.94 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 30.958 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 35.544 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 35.569 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 3 mins 41.947 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 3 mins 41.964 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 46.783 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 99d8bae0b11272d929d7fa1e75bd9184b83707d2:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 3 mins 41.947 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 3 mins 41.964 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 46.783 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 46.818 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 58.926 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 34.405 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 29.903 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 11.742 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 3.405 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 3.422 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 14.117 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 14.145 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 58.926 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 34.405 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 29.903 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 11.742 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 3.405 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 3.422 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 8 mins 14.117 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.779 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.795 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 55.608 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 55.636 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.779 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 3 mins 36.795 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 55.608 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 12.29 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 12.307 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 21.805 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0f1fd1879768f61eddb90660298ffc282d4e071e:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 12.29 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 216 | 1 | 0 | 4 mins 12.307 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 21.805 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 216 | 1 | 0 | 4 mins 21.834 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8bcc53a6d8f08e8415eed93fc3f08021dab39bcf:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 59.137 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 36.777 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 2 | 2 mins 57.584 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 3 mins 6.627 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 18.851 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 4 mins 2.215 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8bcc53a6d8f08e8415eed93fc3f08021dab39bcf:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 2 mins 24.381 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 31.459 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8bcc53a6d8f08e8415eed93fc3f08021dab39bcf:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 39.289 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 97c500d87911e1911f7fff024f01ab8076dee622:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 1 min 0.935 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 37.927 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 10.418 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 20.793 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 3 mins 27.613 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 5 mins 3.197 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 97c500d87911e1911f7fff024f01ab8076dee622:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 48.446 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 97c500d87911e1911f7fff024f01ab8076dee622:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 3.544 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 485bbe04703c8fc22e5bef05884e45577b709a4b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 54.377 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 29.488 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 8.665 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 1.873 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 43.07 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 6 mins 38.75 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 485bbe04703c8fc22e5bef05884e45577b709a4b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 32.6 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 485bbe04703c8fc22e5bef05884e45577b709a4b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 2 | 3 mins 58.852 secs | false | undefined |

**Comment by wmhilton** [comment]
Among (many issues with Edge) the PGP _parser_ isn't working right in Edge. It returns 1 packet instead of 5. Very weird.

**Comment by karma-pr-reporter** [comment]
## Test Results for 8508bc0647a1aa1c44182812bf9875c89bde08ed:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 57.406 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 32.396 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 36.641 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 221 | 1 | 1 | 3 mins 28.579 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 222 | 1 | 0 | 3 mins 55.401 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 4 mins 15.414 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 8508bc0647a1aa1c44182812bf9875c89bde08ed:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 2 mins 46.401 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for a74caa6e8f85b45b1758dcdbda4bb27141d7f02a:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 222 | 1 | 0 | 54.305 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 222 | 1 | 0 | 1 min 32.031 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 222 | 1 | 0 | 2 mins 53.228 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 222 | 1 | 0 | 3 mins 3.434 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 222 | 1 | 0 | 3 mins 30.834 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 221 | 1 | 1 | 8 mins 25.107 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for a74caa6e8f85b45b1758dcdbda4bb27141d7f02a:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Mobile Safari 11.0.0 (iOS 11.2.0) | 222 | 1 | 0 | 4 mins 21.586 secs | false | undefined |

**Pull request merged**
