### PR TITLE
Add badges to display gzip size and install size

### PR DESCRIPTION
**Pull request by styfle**
This adds two new badges to the README:

- **gzip size**: the size of the UMD build after gzip compression
- **install size**: the size of `npm install isomorphic-git` on disk

### CODE REVIEW

**Comment by wmhilton** [comment]
Cool!

**Comment by styfle** [comment]
Anything else I need to do?
It looks like code coverage went down but all I changed was the README file 🤔

**Comment by wmhilton** [comment]
Nope you're good! For some reason the snyk.io bot didn't return a status, and since that is a security scan it's one of the checks that has to pass for me to be able to merge it - I've configured the master branch to forbid merges if Travis, Node Security, or Snyk fail (the CodeCov test is optional and just for information) - but it re-triggered and ran successfully after I merged #190. So now I'll merge it!

**Pull request merged**
