### PR TITLE
feat: Added 'walkBeta2' command

### PR DESCRIPTION
**Pull request by wmhilton**
## I'm adding a new command:

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] add as a new file in `src/commands`
- [x] add command to `src/index.js`
- [x] add TypeScript definition in `src/index.d.ts`
- [x] update `__tests__/__snapshots__/test-exports.js.snap`
- [x] add command to README list of commands
- [x] create a test in `src/__tests__`
- [x] document the command with a JSDoc comment
  - [x] add page to the [Alphabetical Index](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/docs/alphabetic.md)
  - [x] add page to the [sidebar](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/website/sidebars.json)
- [x] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 993668b137375572d40d45278b757fbd7d0eb51f:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 298  | 1    | 0    | 3m:10s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 298  | 1    | 0    | 4m:5s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 298  | 1    | 0    | 1m:50s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 298  | 1    | 0    | 0m:46s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 297  | 2    | 0    | 3m:47s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 298  | 1    | 0    | 4m:18s | false       |

### Longest running tests
- 45.776 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 23.625 secs - fetch fetch (from Github) - _Edge_
- 17.027 secs - GitPackIndex from .pack - _Edge_
- 15.732 secs - GitPackIndex to .idx file from .pack - _Edge_
- 12.83 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 12.306 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 11.34 secs - GitPackIndex from .pack - _Firefox_
- 10.922 secs - fetch shallow fetch (from Github) - _Edge_
- 10.809 secs - fetch fetch (from Github) - _Firefox_
- 10.577 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 10.556 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_

**Comment by karma-pr-reporter** [comment]
## Test Results for 7b39b727afeba143a02381a0b2fd1d79de59ec38:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 298  | 1    | 0    | 3m:5s  | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 298  | 1    | 0    | 4m:4s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 298  | 1    | 0    | 1m:54s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 298  | 1    | 0    | 0m:48s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 0    | 0    | 0    | 1m:55s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 0    | 0    | 0    | 1m:55s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 298  | 1    | 0    | 3m:33s | false       |

### Longest running tests
- 25.275 secs - fetch fetch (from Github) - _Firefox_
- 25.069 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 21.975 secs - fetch fetch (from Github) - _Edge_
- 18.9 secs - fetch shallow fetch (from Github) - _Edge_
- 16.179 secs - GitPackIndex from .pack - _Edge_
- 15.312 secs - GitPackIndex to .idx file from .pack - _Edge_
- 14.58 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 12.557 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 11.288 secs - fetch shallow fetch (from Github) - _Firefox_
- 11.128 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 10.216 secs - fetch shallow fetch since (from Github) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 7b39b727afeba143a02381a0b2fd1d79de59ec38:
| Browser                           | Pass | Skip | Fail | Time  | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ----- | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:5s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:6s | false       |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 7b39b727afeba143a02381a0b2fd1d79de59ec38:
| Browser                           | Pass | Skip | Fail | Time  | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ----- | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:5s | false       |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 7b39b727afeba143a02381a0b2fd1d79de59ec38:
| Browser                           | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:58s | false       |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 7b39b727afeba143a02381a0b2fd1d79de59ec38:
| Browser                           | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:58s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 2m:58s | false       |

### Longest running tests

**Comment by wmhilton** [comment]
kahn meme

**Comment by karma-pr-reporter** [comment]
## Test Results for a97979ae21650da0b40050abb9b0d787b8349107:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 298  | 1    | 0    | 3m:29s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 298  | 1    | 0    | 4m:14s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 298  | 1    | 0    | 1m:53s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 298  | 1    | 0    | 0m:47s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 0    | 0    | 0    | 1m:49s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 0    | 0    | 0    | 1m:49s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 298  | 1    | 0    | 3m:37s | false       |

### Longest running tests
- 39.887 secs - fetch fetch (from Github) - _Edge_
- 21.433 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 18.204 secs - fetch shallow fetch (from Github) - _Edge_
- 13.598 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 13.327 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 12.296 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 11.895 secs - fetch shallow fetch relative (from Github) - _Edge_
- 11.299 secs - GitPackIndex from .pack - _Firefox_
- 10.571 secs - fetch fetch (from Github) - _Chrome Mobile_
- 10.29 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 10.278 secs - fetch shallow fetch (from Github) - _Firefox_

**Comment by karma-pr-reporter** [comment]
## Test Results for a97979ae21650da0b40050abb9b0d787b8349107:
| Browser                           | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 1m:35s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 1m:35s | false       |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for a97979ae21650da0b40050abb9b0d787b8349107:
| Browser                           | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0    | 0    | 0    | 1m:35s | false       |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for 3047696338ddbc2c48057d2d075b8f018596589b:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 298  | 1    | 0    | 3m:33s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 298  | 1    | 0    | 4m:6s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 298  | 1    | 0    | 1m:56s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 298  | 1    | 0    | 0m:48s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 297  | 2    | 0    | 3m:37s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 298  | 1    | 0    | 3m:31s | false       |

### Longest running tests
- 25.459 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 25.077 secs - fetch fetch (from Github) - _Edge_
- 21.614 secs - fetch fetch (from Github) - _Firefox_
- 20.614 secs - fetch shallow fetch (from Github) - _Edge_
- 16.839 secs - GitPackIndex to .idx file from .pack - _Edge_
- 16.683 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 15.611 secs - GitPackIndex from .pack - _Edge_
- 12.961 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 10.252 secs - fetch shallow fetch (from Github) - _Firefox_
- 9.747 secs - fetch shallow fetch relative (from Github) - _Edge_
- 8.554 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_

**Pull request merged**
