### PR TITLE
Handle empty repos which return capabilities

### PR DESCRIPTION
**Pull request by amrc-benmorrow**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

The Git wire protocol has a special hack to support returning capabilities on empty repos. As of Git version 1.43 the git-http-backend is using this, which means we need to support it.

### CODE REVIEW

**Comment by jcubic** [comment]
Can you add unit tests or a reproduction if this is a GitHub issue?

**Comment by jcubic** [comment]
Thanks for adding test. But it seems this is duplication of: https://github.com/isomorphic-git/isomorphic-git/pull/1862 that is tracked in the issue https://github.com/isomorphic-git/isomorphic-git/pull/1862

**Comment by amrc-benmorrow** [comment]
You're right: I didn't find that PR.

It's probably worth keeping the new test even if this PR is rejected; it tests the protocol directly rather than relying on the behaviour of `git`.

What can I do to move forward towards getting this fix into a release?

**Comment by jcubic** [comment]
Sure, you can remove your fix and keep the unit test (also your name in contributor list) we will merge this, when the original PR will be merged.

**Comment by jcubic** [comment]
Sorry about previous comment that suppose to be added to that other PR.

You can remove the fix, because that other PR was just merged, and you can rebase with main so yours is up-to-date.

**Comment by jcubic** [comment]
The linked PR was merged, but the release failed with a timeout error. The Job took too long to run.

**Pull request merged**
