### PR TITLE
fix: statusMatrix() should not show non-files

### LINKED ISSUE #705: statusMatrix() shows non-files
using isomorphic-git with node, having a non-file / non-symlink in the working directory, for example a unix socket, is reported in `statusMartix()` where as `git status` doesn't list it.

### example:

```
$ python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('test.sock')"
$ ls -al
total 0
drwxr-xr-x   6 user staff   192B Feb 28 11:20 ./
drwxr-xr-x  19 user staff   608B Feb 28 11:14 ../
drwxr-xr-x  12 user staff   384B Feb 28 11:17 .git/
lrwxr-xr-x   1 user staff     9B Feb 28 11:29 linktoreadme.md@ -> readme.md
-rw-r--r--   1 user staff     0B Feb 28 11:17 newfile.txt
-rw-r--r--   1 user staff     0B Feb 28 11:15 readme.md
srwxr-xr-x   1 user staff     0B Feb 28 11:20 test.sock=

$ git status --porcelain
?? linktoreadme.md
?? newfile.txt

$ node -e "const git = require('isomorphic-git'); git.plugins.set('fs', require('fs')); git.statusMatrix({dir:'.'}).then(console.log)"
[ [ 'linktoreadme.md', 0, 2, 0 ],
  [ 'newfile.txt', 0, 2, 0 ],
  [ 'readme.md', 1, 1, 1 ],
  [ 'test.sock', 0, 2, 0 ] ]
```

**Expected:** `test.sock` not to be reported in the martix.

### PR DESCRIPTION
**Pull request by katakonst**
## I'm fixing a bug or typo
fixes #705

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 0dd2ee64f021408ed736d8311038c7a8a8d876ab:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 252 | 1 | 0 | 1 min 21.213 secs | false | undefined |
| Firefox 65.0.0 (Ubuntu 0.0.0) | 251 | 1 | 1 | 2 mins 34.741 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 0 | 0 | 0 | 4 mins 30.022 secs | true | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 0 | 0 | 0 | 4 mins 53.811 secs | true | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 0 | 0 | 0 | 6 mins 54.747 secs | true | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 0 | 0 | 0 | 7 mins 30.108 secs | true | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 0dd2ee64f021408ed736d8311038c7a8a8d876ab:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Firefox 65.0.0 (Ubuntu 0.0.0) | 251 | 1 | 1 | 1 min 56.989 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 252 | 1 | 0 | 3 mins 7.851 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 252 | 1 | 0 | 3 mins 27.538 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 252 | 1 | 0 | 5 mins 29.258 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 199 | 1 | 0 | 5 mins 54.538 secs | true | undefined |

**Comment by wmhilton** [comment]
Thank you so much!!!

**Comment by karma-pr-reporter** [comment]
## Test Results for 9f6369393ebd8f528f47f67a1a015c63de1f54a8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 253 | 1 | 0 | 1 min 25.478 secs | false | undefined |
| Firefox 65.0.0 (Ubuntu 0.0.0) | 252 | 1 | 1 | 2 mins 41.964 secs | false | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 253 | 1 | 0 | 3 mins 25.997 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 253 | 1 | 0 | 3 mins 47.698 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 253 | 1 | 0 | 5 mins 3.648 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 253 | 1 | 0 | 5 mins 55.544 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 9f6369393ebd8f528f47f67a1a015c63de1f54a8:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Firefox 65.0.0 (Ubuntu 0.0.0) | 252 | 1 | 1 | 1 min 59.117 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for e537bbcc297566edfff82c575603ad8cb8caea1b:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Firefox 65.0.0 (Ubuntu 0.0.0) | 253 | 1 | 0 | 2 mins 43.512 secs | false | undefined |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 157 | 0 | 0 | 2 mins 48.59 secs | true | undefined |
| Safari 11.1.2 (Mac OS X 10.13.6) | 253 | 1 | 0 | 3 mins 0.62 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 253 | 1 | 0 | 3 mins 46.776 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 253 | 1 | 0 | 5 mins 4.953 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 253 | 1 | 0 | 5 mins 29.728 secs | false | undefined |

**Comment by wmhilton** [comment]
Hmm. The PR comment reporter didn't fire for the second go-round of HeadlessChrome but the log says it did pass: 
```
 - HeadlessChrome 0.0.0 (Linux 0.0.0): 254 tests
   - 253 ok, 1 skipped
```

**Pull request merged**
