### PR TITLE
fix: add HEAD to GetRemoteInfoResult type.

### LINKED ISSUE #1274: HEAD not included in GetRemoteInfoResult type
Hi 👋 

I have noticed that in the [documentation](https://isomorphic-git.org/docs/en/getRemoteInfo) and the [type signature](https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/api/getRemoteInfo.js#L9) for `getRemoteInfo`, there's no `HEAD` present in `GetRemoteInfoResult`. If I run the example given in the docu, `HEAD` is included in the output.

Screenshot 2020-12-04 at 17 37 56

I can also replicate this behavior locally with v1.8.0:

```
> const http = require('isomorphic-git/http/node')
undefined
> let res = git.getRemoteInfo({http, url: 'https://github.com/strangedev/test-zettels.git'})
undefined
> res.then(console.log)
Promise { <pending> }
> {
  capabilities: [
    'multi_ack',
    'thin-pack',
    'side-band',
    'side-band-64k',
    'ofs-delta',
    'shallow',
    'deepen-since',
    'deepen-not',
    'deepen-relative',
    'no-progress',
    'include-tag',
    'multi_ack_detailed',
    'allow-tip-sha1-in-want',
    'allow-reachable-sha1-in-want',
    'no-done',
    'symref=HEAD:refs/heads/master',
    'filter',
    'object-format=sha1',
    'agent=git/github-g574413c1f267'
  ],
  HEAD: 'refs/heads/master',
  refs: { heads: { master: 'eb169f643667fea3fb0fddeca8b9dcce46278f7f' } }
}
```

I am not sure if this is a bug or an incomplete type annotation. I feel, however, that the remote's HEAD should be included in the output, since many people don't use `master` as the default branch anymore. `getRemoteInfo` would be a good way to detect which ref acts as the default branch.

If this is not a bug, I would be happy to contribute updated type definitions.

I am using Node 12.

### PR DESCRIPTION
**Pull request by strangedev**
Fixes #1274.

Unfortunately, I can't run the tests locally due to #1158.
I hope this is how the types are handled by this project, I couldn't find any other type definitions. Please let me know if this works for you or if I should change something :smile_cat:

### CODE REVIEW

**Comment by jcubic** [comment]
Hmm, I was able to run tests with node v12.0.0 it failed but only in 14.

**Comment by jcubic** [comment]
Thanks for updating the types.

**Comment by wmhilton** [comment]
Oops this broke the docs. But should be a simple fix!
image

**Comment by wmhilton** [comment]
Well nevermind, I don't know why it's broke. (Reverting this change doesn't fix it.) I wonder if the jsdoc parser got modified or something. I'll just... not worry about it right now.

**Pull request merged**
