### PR TITLE
feat: Added 'branch' command

### LINKED ISSUE #22: createBranch

### PR DESCRIPTION
**Pull request by bokuweb**
Hi :) It's a very cool project!!
I'd like to use this project as my project as more commands are added.
As an initial contribution, I tried to implement a `branch` command.

Could you please check this PR if you get a chance.

- [x] add as a new file in `src/commands`
  - [x] add command to `src/commands.js`
- [x] add command to README list of commands
- [x] add TypeScript definition in `src/index.d.ts`
- [ ] create a new doc page [docs](https://github.com/isomorphic-git/isomorphic-git.github.io/tree/source/docs)/X.md
  - [ ] add page to the [Alphabetical Index](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/docs/alphabetic.md)
  - [ ] add page to the [sidebar](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/website/sidebars.json)
- [x] create a test in `src/__tests__`
- [x] make a feature commit "feat: Added 'X' command"

TODO: I'll add docs when this PR approved.

### related issue

closes #22

### CODE REVIEW

**Comment by wmhilton** [comment]
Sweeeeeeet!!!!!!!

**Comment by wmhilton** [comment]
I'm at work right now, but tonight I'll give this a review but at first lookover it looks great! My only thought is maybe we should add some branch name validation using https://www.npmjs.com/package/clean-git-ref to prevent users from adding invalid branch names.

**Comment by bokuweb** [comment]
@wmhilton Thanks!! approved 👍

**Pull request merged**
