### PR TITLE
feat(config): Added support for `global` git config

### PR DESCRIPTION
**Pull request by vigan-abd**
## I'm adding a parameter to an existing command X:

- [x] add parameter `global` to the function in `src/api/getConfig.js`, `src/api/getConfigAll.js`, `src/api/setConfig.js`,  `src/commands/getConfig.js`, `src/commands/getConfigAll.js`, and `src/managers/GitConfigManager.js`
- [x] document the parameter in the JSDoc comment above the function
- [ ] add a test case in `__tests__/test-X.js` if possible
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

### CODE REVIEW

**Review by eugeneglova — APPROVED** [review]

**Comment by vigan-abd** [comment]
hi @jcubic seems that some tests are failing because of auth token in gitlabs, could you please check that part and maybe inform us for upcoming steps?

**Comment by jcubic** [comment]
I have no idea what is happening with GitLab, I was hoping that someone will check this out. We had one person that was looking at CI/CD, but so far no one did check it.

I can contact GitLab support, maybe they will be able to help. I have very little knowledge about current CI/CD.

**Comment by vigan-abd** [comment]
maybe we can 

> I have no idea what is happening with GitLab, I was hoping that someone will check this out. We had one person that was looking at CI/CD, but so far no one did check it.
> 
> I can contact GitLab support, maybe they will be able to help. I have very little knowledge about current CI/CD.

ok I've created a new repo in gitlab since access is revoked, now tests should work

**Comment by jcubic** [comment]
I don't think it's a good idea. I will contact original author to get access to:

https://gitlab.com/isomorphic-git/test.empty.git

What exactly is needed?

**Comment by vigan-abd** [comment]
> I don't think it's a good idea. I will contact original author to get access to:
> 
> https://gitlab.com/isomorphic-git/test.empty.git
> 
> What exactly is needed?

they need to generate a new access token for repo and it should solve the issue

**Pull request closed without merging**
