### PR TITLE
feat: Added 'addNote', 'listNotes', 'removeNote', and 'readNote' commands

### LINKED ISSUE #958: Notes support
Implement basic git notes, all under a supplied notes ref:

* addNote as string or byte array to any object.  Ignore merge and move scenarios for now.
* listNotes (all or one)
* removeNote
* showNote return a note as a Buffer.

### PR DESCRIPTION
**Pull request by djencks**
resolves #958

This implements basic git notes support with addNote, listNotes, removeNote, and showNote commands.

I didn't see a plausible way to combine all this into one command with subcommands as in regular git.  

There is no support for merging notes or moving a note is the notated object is moved.

## I'm adding a new command:

- [x] add as a new file in `src/commands`
- [x] add command to `src/index.js`
- [x] add TypeScript definition in `src/index.d.ts`
- [x] update `__tests__/__snapshots__/test-exports.js.snap`
- [x] add command to README list of commands
- [x] create a test in `src/__tests__`
- [x] document the command with a JSDoc comment
  - [ ] add page to the [Alphabetical Index](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/docs/alphabetic.md)
  - [ ] add page to the [sidebar](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/website/sidebars.json)
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 8152b9af5bd31099b29cc8c42eb2bf3994bbf390:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 338  | 1    | 0    | 2m:42s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 338  | 1    | 0    | 4m:58s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 338  | 1    | 0    | 2m:2s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 338  | 1    | 0    | 0m:53s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 337  | 2    | 0    | 2m:28s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 338  | 1    | 0    | 3m:24s | false       |

### Longest running tests
- 22.586 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 18.981 secs - fetch shallow fetch relative (from Github) - _Edge_
- 18.579 secs - fetch shallow fetch (from Github) - _Firefox_
- 18.319 secs - GitPackIndex from .pack - _Edge_
- 18.281 secs - fetch fetch (from Github) - _Edge_
- 16.905 secs - GitPackIndex to .idx file from .pack - _Edge_
- 14.573 secs - fetch fetch (from Github) - _Firefox_
- 13.565 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 12.437 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 12.311 secs - fetch shallow fetch since (from Github) - _Edge_
- 12.04 secs - fetch shallow fetch relative (from Github) - _Firefox_

**Comment by wmhilton** [comment]
Wow! OK I will check this out closely this weekend; I haven't even heard of the 'notes' feature before.

**Comment by wmhilton** [comment]
Thank you for introducing me to `git note`! This is _so_ interesting. I agree this is an awesome feature to include in `isomorphic-git`. I want to tweak the code a bit and change up the tests first, but it shall be in the next release for sure!

> I didn't see a plausible way to combine all this into one command with subcommands as in regular git.

Good eye! Yes, I've pretty much abandoned the "subcommand" idea - it ends up making more work in JavaScript. `addNote`, `listNotes` etc is just fine, and matches the current API patterns for files, refs, branches, etc.

**Comment by karma-pr-reporter** [comment]
## Test Results for a06fe0b3c3d86c96bb29f8286150985cd19bfd8d:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 367  | 1    | 0    | 2m:23s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 367  | 1    | 0    | 4m:17s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 367  | 1    | 0    | 2m:2s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 367  | 1    | 0    | 0m:57s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 366  | 2    | 0    | 2m:26s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 367  | 1    | 0    | 3m:32s | false       |

### Longest running tests
- 29.873 secs - fetch fetch (from Github) - _Firefox_
- 24.676 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 24.403 secs - fetch shallow fetch relative (from Github) - _Edge_
- 23.313 secs - fetch fetch (from Github) - _Edge_
- 19.677 secs - GitPackIndex to .idx file from .pack - _Edge_
- 18.26 secs - GitPackIndex from .pack - _Edge_
- 13.378 secs - fetch shallow fetch (from Github) - _Firefox_
- 13.328 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 10.624 secs - fetch shallow fetch (from Github) - _Edge_
- 10.396 secs - fetch shallow fetch since (from Github) - _Edge_
- 9.657 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 0d804246bd7a2d838cde01cb198ade2acda74341:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 371  | 1    | 0    | 2m:32s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 371  | 1    | 0    | 4m:23s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 371  | 1    | 0    | 2m:0s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 370  | 1    | 1    | 0m:54s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 370  | 2    | 0    | 2m:34s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 371  | 1    | 0    | 3m:38s | false       |

### Erroring Tests

- HeadlessChrome 0.0.0 (Linux 0.0.0):
  - annotatedTag creates a signed tag to HEAD

### Longest running tests
- 46.041 secs - fetch fetch (from Github) - _Edge_
- 24.816 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 23.694 secs - fetch shallow fetch (from Github) - _Edge_
- 17.723 secs - fetch shallow fetch relative (from Github) - _Edge_
- 14.981 secs - fetch fetch (from Github) - _Firefox_
- 13.762 secs - fetch shallow fetch (from Github) - _Firefox_
- 13.687 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 13.182 secs - fetch fetch (from Github) - _Chrome Mobile_
- 12.501 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 11.508 secs - GitPackIndex from .pack - _Firefox_
- 11.264 secs - fetch shallow fetch exclude (from Github) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 0d804246bd7a2d838cde01cb198ade2acda74341:
| Browser                            | Pass | Skip | Fail | Time   | Disconnect? |
| ---------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 371  | 1    | 0    | 0m:49s | false       |

### Longest running tests
- 6.565 secs - fetch shallow fetch (from Github) - _HeadlessChrome_
- 4.915 secs - fetch shallow fetch relative (from Github) - _HeadlessChrome_
- 3.658 secs - GitPackIndex to .idx file from .pack - _HeadlessChrome_
- 3.491 secs - GitPackIndex from .pack - _HeadlessChrome_
- 3.473 secs - fetch fetch (from Github) - _HeadlessChrome_
- 2.272 secs - Hosting Providers GitHub push - _HeadlessChrome_
- 2.117 secs - Hosting Providers GitLab push - _HeadlessChrome_
- 2.095 secs - Hosting Providers AWS CodeCommit push - _HeadlessChrome_
- 2.017 secs - fetch shallow fetch exclude (from Github) - _HeadlessChrome_
- 1.579 secs - fetch shallow fetch using autoTranslateSSH param (from Github) - _HeadlessChrome_
- 1.332 secs - fetch shallow fetch using autoTranslateSSH config (from Github) - _HeadlessChrome_

**Comment by karma-pr-reporter** [comment]
## Test Results for fb8a9ceaf3da4fa364d7f56678609795b4cde1f1:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 374  | 1    | 0    | 2m:58s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 374  | 1    | 0    | 5m:21s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 374  | 1    | 0    | 1m:44s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 374  | 1    | 0    | 0m:51s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 373  | 2    | 0    | 2m:31s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 374  | 1    | 0    | 3m:37s | false       |

### Longest running tests
- 46.484 secs - fetch fetch (from Github) - _Edge_
- 25.5 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 23.538 secs - fetch shallow fetch (from Github) - _Edge_
- 19.536 secs - fetch shallow fetch relative (from Github) - _Edge_
- 16.119 secs - fetch fetch (from Github) - _Firefox_
- 15.995 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 13.579 secs - fetch shallow fetch (from Github) - _Firefox_
- 11.236 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 10.02 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 8.5 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 8.49 secs - fetch shallow fetch exclude (from Github) - _Edge_

**Comment by wmhilton** [comment]
I know I wrote you isomorphic-git-bot, but boy you chime in at the most random times.

**Comment by karma-pr-reporter** [comment]
## Test Results for 72960e2d88440d1298b7fdf2b93a4c907bfde3c1:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 374  | 1    | 0    | 1m:55s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 374  | 1    | 0    | 4m:31s | false       |
| Firefox 70.0.0 (Ubuntu 0.0.0)           | 374  | 1    | 0    | 2m:2s  | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 374  | 1    | 0    | 0m:58s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 373  | 2    | 0    | 1m:59s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 374  | 1    | 0    | 3m:0s  | false       |

### Longest running tests
- 34.622 secs - fetch fetch (from Github) - _Edge_
- 26.894 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 26.884 secs - fetch shallow fetch (from Github) - _Edge_
- 16.607 secs - fetch shallow fetch relative (from Github) - _Edge_
- 15.072 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 14.443 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 13.641 secs - fetch shallow fetch using autoTranslateSSH config (from Github) - _Edge_
- 13.48 secs - fetch shallow fetch (from Github) - _Firefox_
- 13.429 secs - fetch shallow fetch using autoTranslateSSH param (from Github) - _Edge_
- 13.312 secs - fetch fetch (from Github) - _Firefox_
- 11.908 secs - GitPackIndex from .pack - _Firefox_

**Pull request merged**
