### PR TITLE
Fix octal escape sequences are not allowed in template strings

### LINKED ISSUE #1032: Octal escape sequences are not allowed in template strings
Hi @wmhilton , thanks for your work. I like this library so mush.
```javascript
import * as git from 'isomorphic-git/dist/for-node/isomorphic-git/index'

const pushRes = await git.push({
  fs,
  dir: this.outputDir,
  remote: 'origin',
  ref: setting.branch,
  force: true,
})
```
when I use push method, it's work fine in development env, but build is failed.(electron build)
image

Can you help me?

### PR DESCRIPTION
**Pull request by EryouHao**
Octal escape sequences are not allowed in template strings

Closes #1032

## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for a62d85822e764fd343cab861d24ab7b51a7e1386:
| Browser                            | Pass | Skip | Fail | Time   | Disconnect? |
| ---------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Edge 17.17134.0 (Windows 10 0.0.0) | 382  | 1    | 0    | 4m:21s | false       |
| Firefox 72.0.0 (Ubuntu 0.0.0)      | 382  | 1    | 0    | 1m:40s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 382  | 1    | 0    | 0m:52s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)  | 381  | 2    | 0    | 2m:26s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)   | 382  | 1    | 0    | 3m:41s | false       |

### Longest running tests
- 32.487 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 28.412 secs - fetch shallow fetch relative (from Github) - _Edge_
- 25.067 secs - fetch fetch (from Github) - _Edge_
- 24.8 secs - fetch shallow fetch (from Github) - _Edge_
- 13.368 secs - fetch shallow fetch relative (from Github) - _Firefox_
- 12.864 secs - fetch shallow fetch using autoTranslateSSH config (from Github) - _Edge_
- 12.081 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 11.951 secs - fetch fetch (from Github) - _Firefox_
- 11.389 secs - fetch shallow fetch exclude (from Github) - _Edge_
- 11.054 secs - fetch shallow fetch since (from Github) - _Edge_
- 10.329 secs - GitPackIndex from .pack - _Firefox_

**Comment by karma-pr-reporter** [comment]
## Test Results for a62d85822e764fd343cab861d24ab7b51a7e1386:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by karma-pr-reporter** [comment]
## Test Results for a62d85822e764fd343cab861d24ab7b51a7e1386:
| Browser | Pass | Skip | Fail | Time | Disconnect? |
| ------- | ---- | ---- | ---- | ---- | ----------- |

### Longest running tests

**Comment by wmhilton** [comment]
None of these are octal sequences. They are hexadecimal sequences and should be perfectly valid in template literals. Therefore, this must be a bug in terser. What exact version of terser are you using? Maybe I can help report and fix the problem to Terser.

**Comment by wmhilton** [comment]
Or are you using a really old version of `isomorphic-git`? This exact error happened in 2018 https://github.com/isomorphic-git/isomorphic-git/pull/571 and was already fixed.

**Comment by wmhilton** [comment]
Pretty sure you must be using an old version. 🤷‍♂

**Pull request closed without merging**
