### PR TITLE
Try using ChromeHeadless on Travis again

### PR DESCRIPTION
**Pull request by wmhilton**

### CODE REVIEW

**Comment by wmhilton** [comment]
```
12 05 2018 19:14:32.471:ERROR [launcher]: Cannot start ChromeHeadless
	[0512/191431.976815:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x564ca05c982c base::debug::StackTrace::StackTrace()
#1 0x564ca0550290 logging::LogMessage::~LogMessage()
#2 0x564c9f5465d1 content::ZygoteHostImpl::Init()
#3 0x564ca027fd91 content::ContentMainRunnerImpl::Initialize()
#4 0x564ca0289c12 service_manager::Main()
#5 0x564ca027e184 content::ContentMain()
#6 0x564ca4456a39 headless::(anonymous namespace)::RunContentMain()
#7 0x564ca4456ac2 headless::HeadlessBrowserMain()
#8 0x564ca0286f8f headless::HeadlessShellMain()
#9 0x564c9e7ff1ac ChromeMain
#10 0x7f4d65cd8f45 __libc_start_main
#11 0x564c9e7ff02a _start
Received signal 6
#0 0x564ca05c982c base::debug::StackTrace::StackTrace()
#1 0x564ca05c9391 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f4d6b962330 <unknown>
#3 0x7f4d65cedc37 gsignal
#4 0x7f4d65cf1028 abort
#5 0x564ca05c81e5 base::debug::BreakDebugger()
#6 0x564ca05506da logging::LogMessage::~LogMessage()
#7 0x564c9f5465d1 content::ZygoteHostImpl::Init()
#8 0x564ca027fd91 content::ContentMainRunnerImpl::Initialize()
#9 0x564ca0289c12 service_manager::Main()
#10 0x564ca027e184 content::ContentMain()
#11 0x564ca4456a39 headless::(anonymous namespace)::RunContentMain()
#12 0x564ca4456ac2 headless::HeadlessBrowserMain()
#13 0x564ca0286f8f headless::HeadlessShellMain()
#14 0x564c9e7ff1ac ChromeMain
#15 0x7f4d65cd8f45 __libc_start_main
#16 0x564c9e7ff02a _start
  r8: 00007f4d6bd5ba00  r9: 00001dbf3d55b800 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007fffd30bba38 r13: 0000000000000161 r14: 00007fffd30bba40 r15: 00007fffd30bb5d9
  di: 0000000000001051  si: 0000000000001051  bp: 00007fffd30bb580  bx: 00007fffd30bb5f0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f4d65cedc37  sp: 00007fffd30bb448
  ip: 00007f4d65cedc37 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

@DanielRuf thoughts?

**Comment by DanielRuf** [comment]
Looks good, just `--no-sandbox` missing.

**Comment by DanielRuf** [comment]
See https://github.com/karma-runner/karma/issues/2652

**Comment by DanielRuf** [comment]
And especially https://github.com/karma-runner/karma/issues/2652#issuecomment-332872294

**Comment by DanielRuf** [comment]
It's a security feature of Chromium and its sandbox ;-)
Unfortunately it causes issues on CI in many cases.

**Comment by wmhilton** [comment]
I appreciate your expert guidance. I would have given up if you hadn't been there to say "Looks good! Just needs this one little thing"

**Comment by DanielRuf** [comment]
Passed =)

**Comment by DanielRuf** [comment]
https://travis-ci.org/isomorphic-git/isomorphic-git/jobs/378173890

**Comment by wmhilton** [comment]
Yup, I'm just going to disable the remote SauceLabs testing for Chrome, since we can run it locally now, and give up on displaying a dynamic browser matrix in the README and just hard-code one lol.

**Comment by DanielRuf** [comment]
> I appreciate your expert guidance. I would have given up if you hadn't been there to say "Looks good! Just needs this one little thing"

Great collaboration =) And there is always a solution ;-)

**Pull request merged**
