### PR TITLE
docs: add 🐊Putout

### PR DESCRIPTION
**Pull request by coderaiser**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

## I'm adding a parameter to an existing command X:

- [ ] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [ ] document the parameter in the JSDoc comment above the function
- [ ] add a test case in `__tests__/test-X.js` if possible
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

## I'm adding a new command:

- [ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [ ] add command to `src/index.js`
- [ ] update `__tests__/test-exports.js`
- [ ] create a test in `src/__tests__`
- [ ] document the command with a JSDoc comment
- [ ] add page to the Docs Sidebar `website/sidebars.json`
- [ ] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by jcubic** [comment]
Can you delete the emoji? Unless it's part of the name. Looking at the repo it's not.

**Comment by coderaiser** [comment]
That's part of name

**Comment by jcubic** [comment]
The title of the repo doesn't have this emoji in the name.

**Comment by coderaiser** [comment]
It has all mentions of 🐊**Putout**, under the title there is logo, I think enough crocodiles for one screen of text :)

**Comment by coderaiser** [comment]
I add emoji not to stand off, it's part of the name, I don't know how `git` deals with emoji, why I should name git repo like name of library?

**Comment by jcubic** [comment]
This is the name of the library I don't see any emoji:

Przechwycenie obrazu ekranu_2023-06-13_18-31-54

**Comment by coderaiser** [comment]
Try to read documentation a bit 😏

**Comment by coderaiser** [comment]
https://github.com/coderaiser/putout/releases/tag/v29.14.0

**Comment by jcubic** [comment]
I'm OK in adding your project like this if you update the title of the repo.

**Pull request closed without merging**
