### PR TITLE
Patch use .cjs instead of .js for test

### PR DESCRIPTION
**Pull request by sosuisen**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "fix: use .cjs instead of .js for test"

---
This is a pull request for 
#1434

### CODE REVIEW

**Comment by jcubic** [comment]
Build failed.

https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=2438&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b&l=125

**Comment by sosuisen** [comment]
I have resolved the failure by applying the result of eslint --fix .

> Build failed.
> 
> https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=2438&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b&l=125

**Comment by jcubic** [comment]
There are still errors, You've updated the NPM packages, and now ESlint report errors. I think they need to be fixed by hand since it's the order of imports.

https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=2439&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b&l=75

**Comment by sosuisen** [comment]
I'm sorry, but it seems impossible to fix all lint errors in my local environment.

For this PR, eslint is passing in my local environment, and I don't get any error about import order. Perhaps the version is different from the eslint on the dev.azure.com side, but I can't be sure of that.

**Comment by jcubic** [comment]
Most ESLint errors came from sort-imports rule, maybe this is something new that was added. in 

https://eslint.org/docs/rules/sort-imports

https://github.com/isomorphic-git/isomorphic-git/blob/main/.eslintrc.json

It seems that the options changed, they look different than in documentation.

Can you update the options to match? Or if you don't want to do that just remove changes that you did to package-lock.json since there are no updates to eslint in package.json those errors may come from a new version of ESLint that is a lock file.

**Comment by sosuisen** [comment]
Okay, I got it.

- I have reverted my npm v7.21.1 to v6.14.15 to use lockfileVersion 1.
- I have kept the original package-lock.json as much as possible.

Eslint passes on my environment, but still fails in the test above.

**Comment by jcubic** [comment]
There are still issues with ESLint. What I would do is to run squash to create single commit then git reset and remove the file from the commit, commit again and push force:

```bash
git rebase -i 76d0d69b9044bb6b38d247ba34c3a9a88b70036c
## IN EDITOR use squash for every commit
git reset HEAD~1
git checkout package-lock.json
git checkout 
git commit -am '<put commit message here>'
```
This should fix the issue. And also if you have any changes to eslit config you can remove those changes as well.

**Comment by sosuisen** [comment]
That seems to solve the ESLint problem, but it does not solve #1434.

The original package-lock.json cannot be used as-is. To solve the problem #1434, it is essential to update prettier and jest modules, as described below.
https://github.com/isomorphic-git/isomorphic-git/issues/1434#issuecomment-959128432

**Comment by sosuisen** [comment]
I don't understand why I get the ESLint error **"There should be no empty line within import group import/order"** above, even though the .eslintrc.json of the original and my patch are both `"newlines-between": "always"` in  `"import/order"` block and the version of eslint in package-lock.json is the same.

https://github.com/isomorphic-git/isomorphic-git/blob/main/.eslintrc.json
https://github.com/sosuisen/isomorphic-git/blob/patch-use-cjs-for-test/.eslintrc.json

`"newlines-between": "always"` inserts a new line within import group. The error message is wrong because the new line is there as per ESLint rules.

**Comment by jcubic** [comment]
I'm closing this issue because of conflicts. If you want and can solve the issue please create another PR.

**Pull request closed without merging**
