### PR TITLE
feat: Added 'parallel' parameter

### PR DESCRIPTION
**Pull request by barry963**
## I'm fixing a bug or typo

- [] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [] squash merge the PR with commit message "fix: [Description of fix]"

## I'm adding a parameter to an existing command X:

- [x] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [x] document the parameter in the JSDoc comment above the function
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

## I'm adding a new command:

- [ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [ ] add command to `src/index.js`
- [ ] update `__tests__/test-exports.js`
- [ ] create a test in `src/__tests__`
- [ ] document the command with a JSDoc comment
- [ ] add page to the Docs Sidebar `website/sidebars.json`
- [ ] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by barry963** [comment]
I add this parameter `sequentialize` as I would like to provide a parameter that makes the library consumes less memory in git add operation. 

I find that if I use the lib in aws small instance such as t2.micro with only 1GB memory, git add operation against large repo (e.g. https://github.com/aws/aws-cdk) will consume lots of memory as the function tries to parallellize file processing by using `Promise.all`. The os will kill the process once the memory consumption is too large, so I add this parameter to reduce the consumption in such situation.

**Comment by jcubic** [comment]
Instead of sequensilize and negating I would just reverse the flag and use `parallel`. What you think?

**Comment by barry963** [comment]
Done, just update the parameter to `parallel`, thanks

**Comment by jcubic** [comment]
Looks good, thanks for your contribution.

**Pull request merged**
