### PR TITLE
feat: add flag to turn off fast forward merges

### PR DESCRIPTION
**Pull request by SamVerschueren**
This PR adds an option to `merge` and `pull` to skip fast forwards by setting `fastForward: false`. This is in line with the `--no-ff` flag in [merge](https://git-scm.com/docs/git-merge#_options) and [pull](https://git-scm.com/docs/git-pull#_options_related_to_merging).

I also noticed that there where no tests for `pull` at all, so added some together with tests for `fastForward: false`.  The changes itself our very minimal. Most of the files are fixtures.

## I'm adding a parameter to an existing command X:

- [x] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [x] document the parameter in the JSDoc comment above the function
- [x] add a test case in `__tests__/test-X.js` if possible
- [x] squash merge the PR with commit message "feat: add flag to turn off fast forward merges"

### CODE REVIEW

**Comment by mojavelinux** [comment]
Seems reasonable to me. And I appreciate the additional tests very much.

Unrelated to this particular issue, I would like to see if we could find a way to avoid having to commit all these fixture repositories. I think doing it this way makes the tests difficult to maintain. I don't see why we could have a test helper that created the repository under test dynamically. It's also easier to see what the fixture contains. If you join https://gitter.im/isomorphic-git/Lobby we could discuss it there. It shouldn't block this issue.

**Comment by jcubic** [comment]
How about we mark all fixtures as binary in `.gitatributes`?

**Comment by SamVerschueren** [comment]
Joined Gitter!

Also, tests seem to fail but I think they are unrelated 🤔 . I'm not able to restart them unless I commit something?

**Comment by jcubic** [comment]
The tests are failing, I have no idea why. Something with Azure DevOps.

**Pull request merged**
