### PR TITLE
Add codespell: workflow, config and fix typos it finds

### PR DESCRIPTION
**Pull request by yarikoptic**
## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README

I first want to check if that is something you would take in

- [ ] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by jcubic** [comment]
There was a fix in unit tests, can you rebase with main?

**Comment by yarikoptic** [comment]
rebased/force-pushed (no new typos were found by codespell).

```sh
❯ npm run add-contributor

> isomorphic-git@0.0.0-development add-contributor
> nps contributors.add

sh: 1: nps: not found
```

It is ok for me to not be added for this contribution.

**Comment by jcubic** [comment]
To add contributor you can try to run:

```
npx nps contributors.add
```
it's the command from package.json. npx will install `nps` if not installed.

Or you use run `npm install -g nps` to install nps globally. I think it should be included in dev dependencies.

**Comment by jcubic** [comment]
I don't think I can merge your PR because you fixed commit messages in unit tests. Now test fails because there are git repositories with fixed commit messages. If you fix the commit message in the source code of the test it now fails to compare if fixture git repositories.

So if you want to modify __tests__ directory it need to update each __fixtures__ by hand.

**Comment by jcubic** [comment]
Some of the fixtures are git repositories with commit history. So you need to run an interactive rebase on those repositories and update each message to match the `__tests__` code. Also if you update the commit messages the hashes will change and if the tests will fail you will need to update the hashes in unit tests.

You can run tests with:

```
npx nps test.setup && npx nps test.jest
```

**Comment by yarikoptic** [comment]
- included only some fixes to tests which are not concerning with fixtures etc
- excluded `__tests__` from codespell as well
- did manage to add myself as contributor. Said for `doc` as the least distant type I think to this kind of contribution ;-)

**Comment by jcubic** [comment]
Thanks for your PR. What is the code in the commit message that starts with `[DATALAD RUNCMD]`? Do I need to include that when I squash the commits?

**Comment by yarikoptic** [comment]
Thanks for asking!

It is our `datalad run` record so anyone could redo that operation later on, e.g. using `datalad rerun` (ref: https://handbook.datalad.org/en/latest/basics/basics-run.html).

You are welcome to trim it anyway you like since in squashed version it would not be sufficient to represent all the changes in that squashed commit anyways.

**Comment by jcubic** [comment]
Hey @yarikoptic, Spellcheck workflow to run automatically, it needs to be approved when someone creates a PR. Do you think you can fix this?

**Pull request merged**
