### PR TITLE
fix: change currentBranch to return undefined if HEAD is detached

### LINKED ISSUE #622: Add feature to check whether HEAD is detached
When working with branches, it's sometimes necessary to know when the repository is not on a branch (detached HEAD). Add a feature to check for this state.

The most logical place for this would be currentBranch, IMO. If the repository is not on a branch, this function should return a falsy value (perhaps undefined). (If you really want the commit of the detached HEAD, you can use resolveRef directly).

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #622

## I'm fixing a bug or typo

- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for ed16f49aa3013d145438a650f48117df9e37943d:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 93 | 1 | 0 | 33.968 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 112 | 0 | 0 | 52.67 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 3 | 0 | 0 | 54.785 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 54 | 0 | 0 | 1 min 30.733 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 144 | 1 | 0 | 3 mins 37.246 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 159 | 1 | 0 | 5 mins 7.622 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for ed16f49aa3013d145438a650f48117df9e37943d:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| Firefox 63.0.0 (Ubuntu 0.0.0) | 112 | 1 | 0 | 37.905 secs | false | undefined |
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 190 | 1 | 0 | 49.604 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 159 | 1 | 0 | 2 mins 24.433 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 106 | 0 | 0 | 2 mins 27.888 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 2 mins 54.474 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 224 | 1 | 0 | 2 mins 54.485 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 150 | 0 | 1 | 3 mins 42.024 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for a42a92fd8050c4b4f511a59d52696d58dc184836:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 80 | 1 | 0 | 34.427 secs | false | undefined |
| Firefox 63.0.0 (Ubuntu 0.0.0) | 169 | 1 | 0 | 1 min 23.348 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 53 | 0 | 0 | 1 min 41.763 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 12 | 0 | 0 | 1 min 43.899 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 224 | 1 | 0 | 2 mins 56.14 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 199 | 1 | 0 | 3 mins 51.065 secs | false | undefined |

**Comment by wmhilton** [comment]
Now technically, this is a breaking change. But I'm willing to bet nobody was relying on that behavior. Plus it has a very simple fix: use `resolveRef({ ref: 'HEAD' })` instead of `currentBranch`.

**Comment by wmhilton** [comment]
I made it a `feat` change instead of a `fix` just in case.

**Pull request merged**
