### PR TITLE
Updating readme with Azure Pipelines badges

### PR DESCRIPTION
**Pull request by chrisrpatterson**
Adding Azure Pipelines badges to readme in place of the travis-ci badges.

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 391a052c0344648b6e02c33e2c278a53ac1d863d:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 53.836 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 28.498 secs | false | undefined |

**Comment by wmhilton** [comment]
Ah. Seeing the tests fail reminds me @chrisrpatterson, I'm on a quest! I want to make PRs from forks work better. (See origin of quest [here](https://github.com/isomorphic-git/isomorphic-git/pull/549#issuecomment-435268162)) It's about those pesky environment variables, secrets, and forks.

**Ideal solution**: a button that says "trust this PR with environment vars and rerun tests." The ideal solution would require adding that feature to Azure Pipelines I believe. Although if it exposed a button on the Github page that would be nice.

**Workaround solution**: can I break my current pipeline into two pipelines, one that runs tests and one that runs semantic release? If so, then for the Test pipeline I could check the box "Edit" > "Triggers" > "Pull request validation" > "Make secrets available to build of forks" and only expose these secrets:

```yaml
      BROWSER_STACK_ACCESS_KEY: $(Browser.Stack.Access.Key)
      BROWSER_STACK_USERNAME: $(Browser.Stack.Username)
      BUNDLESIZE_GITHUB_TOKEN: $(Bundlesize.Github.Token)
      SAUCE_ACCESS_KEY: $(Sauce.Access.Key)
      SAUCE_USERNAME: $(Sauce.Username)
```

but NOT check that box in the Publish pipeline, so that malicious forks can't steal my Github, NPM, and Twitter account tokens:

```yaml
      GH_TOKEN: $(Gh.Token)
      NPM_TOKEN: $(Npm.Token)
      TWITTER_ACCESS_TOKEN_SECRET: $(TWITTER_ACCESS_TOKEN_SECRET)
      TWITTER_CONSUMER_SECRET: $(TWITTER_CONSUMER_SECRET)
```

**Comment by chrisrpatterson** [comment]
@wmhilton yes secrets and forks or at least code from unknown/untrusted users is a challenge.

We are working on a feature where you can delay the build of the PR until a contributor on the repo either creates a label or issues a comment in the PR like /AzurePipelines run all.  We expect to have that available for preview in the next 6 weeks.

Your option today is to create a second pipeline that only does your releases and have that not trigger of PRs from forks.  To do that you will need to click in the link in the New Pipeline wizard and go to the visual designer where you can select the YAML template and then provide a path to the yaml file in the repo.  You can see a setup like this in the Atom repo https://github.com/atom/atom/tree/master/script/vsts where they are also taking advantage of templates to ease maintenance.

**Comment by wmhilton** [comment]
> We are working on a feature where you can delay the build of the PR until a contributor on the repo either creates a label or issues a comment in the PR like /AzurePipelines run all. We expect to have that available for preview in the next 6 weeks.

Eeeeeeeeee! #SquealLikeAnExcitedChildOnChristmas

**Comment by karma-pr-reporter** [comment]
## Test Results for f0f10e76313f290e11d4d09281bd3e26e6de750f:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 53.931 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 27.246 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 2 mins 31.6 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 3 mins 7.405 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 0 | 3 mins 58.603 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 4 mins 30.818 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for f0f10e76313f290e11d4d09281bd3e26e6de750f:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 59.902 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 33.945 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 2 mins 50.518 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 3 mins 5.251 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 0 | 3 mins 35.334 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 4 mins 7.554 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for f0f10e76313f290e11d4d09281bd3e26e6de750f:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 52.458 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 22.639 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 2 mins 11.327 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 2 mins 57.645 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 0 | 4 mins 0.64 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 4 mins 33.813 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for 2ce57290ffdf1c3bb42be77d647464728cdcc2a9:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 59.658 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 35.1 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 2 mins 47.485 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 3 mins 7.889 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 0 | 3 mins 36.282 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 5 mins 6.35 secs | false | undefined |

**Comment by karma-pr-reporter** [comment]
## Test Results for ad34eafeaabb41aa8d7740d66cb5742b63ca0dc7:
| Browser | Passed | Skipped | Failed | Time | Disconnected | Error |
|---------|--------|---------|--------|------|--------------|-------|
| HeadlessChrome 0.0.0 (Linux 0.0.0) | 220 | 1 | 0 | 56.023 secs | false | undefined |
| Firefox 62.0.0 (Ubuntu 0.0.0) | 220 | 1 | 0 | 1 min 34.288 secs | false | undefined |
| Safari 12.0.0 (Mac OS X 10.13.6) | 220 | 1 | 0 | 5 mins 50.377 secs | false | undefined |
| Edge 17.17134.0 (Windows 10 0.0.0) | 220 | 1 | 0 | 6 mins 25.616 secs | false | undefined |
| Chrome Mobile 67.0.3396 (Android 7.1.1) | 220 | 1 | 0 | 6 mins 46.509 secs | false | undefined |
| Mobile Safari 11.0.0 (iOS 11.2.0) | 220 | 1 | 0 | 6 mins 49.19 secs | false | undefined |

**Pull request merged**
