### PR TITLE
feat(add): Merge deletions support

### PR DESCRIPTION
**Pull request by DanilKazanov**
This PR adds merge deletions support to isomorhic-git. if a file that was deleted in another branch is modified in one branch, `MergeConflictError` is returned with the data. 
For example, I have repo with two branches: `master` and `develop`, and file `a`. Then I change file `a` in `master` and delete file `a` in branch `develop`.

#### With native git:
- Native git status:
```shell
$ git status
On branch master
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by them: a

no changes added to commit (use "git add" and/or "git commit -a")
``` 
- Native git status --short:
```shell
$ git status --short
UD a
```

- isomorphic-git statusMatrix:
`[ 'a', 1, 1, 3 ]`

#### With isomorphic-git:
- Native git status:
```shell
$ git status
On branch master
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by them: a

no changes added to commit (use "git add" and/or "git commit -a")
```
- Native git status --short:
```shell
$ git status --short
UD a
```
- isomorphic-git statusMatrix:
`[ 'a', 1, 1, 3 ]`

As you can see, they are the same.

#### With native git:
- Native git status:
```shell
$ git status
On branch develop
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by us:   a

no changes added to commit (use "git add" and/or "git commit -a")
``` 
- Native git status --short:
```shell
$ git status --short
DU a
```

- isomorphic-git statusMatrix:
`[ 'a', 0, 2, 3 ]`

#### With isomorphic-git:
- Native git status:
```shell
$ git status
On branch develop
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by us:   a

no changes added to commit (use "git add" and/or "git commit -a")
```
- Native git status --short:
```shell
$ git status --short
DU a
```
- isomorphic-git statusMatrix:
`[ 'a', 0, 2, 3 ]`

As you can see, they are the same too.

Also, if file `a` has been deleted in both branches, it is simply not a conflict and it is resolved automatically (removed from the index).

The `MergeConflictError` error now has this data: `{ filepaths: string[], bothModified: string[], deleteByUs: string[], deleteByTheirs: string[] }`. Also, I added more branches in test-merge fixture repository.

From my experience, there is only one variant of conficts left: when the same file is added in different branches. But, I don't really understand how to solve this, because diff3 algorithm needs 3 files, so it needs a base file as well. The native git somehow knows how to build a base file from two files, or it uses some other diff algorithm. I had ideas to implement via diff-lines (already in the isomorphic-git dependencies), but I can't be sure how native this is. I'd have to change mergeDriver, since it won't return the base file in such cases.

And another difference I've noticed is the renaming. The native git can realize that a file has been renamed in one branch and in another, and will create a conlifct. (For example, I do `mv a a2` in `master` and `mv a a3` in `develop`. Native-git in merge will create a conflict, isomorphic-git will not. For isomorphic, it is deleting in two branches, adding `a2` and `a3`

### CODE REVIEW

**Comment by DanilKazanov** [comment]
I have no idea why tests are failing. First time I cloned isomorpgic-git, run `npm i`, ran the tests, they failed.

**Comment by jcubic** [comment]
Thanks for the PR. Can you fix the lint errors?

I'm not sure if the tests work locally, there were some fixed done but I'm not sure if they work. The CI/CD failed on lint errors. If tests fail you can use this PR to fix the tests.

**Comment by jcubic** [comment]
now tests are failing, what exactly is `.rejects` in unit tests?

**Comment by DanilKazanov** [comment]
> now tests are failing, what exactly is `.rejects` in unit tests?

https://jestjs.io/docs/asynchronous#asyncawait

**Comment by DanilKazanov** [comment]
the tests seemed to pass

**Comment by jcubic** [comment]
AFAIK the proper API in jest to test if something throws is:

`expect(() => call()).toThrow()` see docs: https://jestjs.io/docs/expect#tothrowerror

**Comment by DanilKazanov** [comment]
> AFAIK the proper API in jest to test if something throws is:
> 
> `expect(() => call()).toThrow()` see docs: https://jestjs.io/docs/expect#tothrowerror

I did the same thing as the other tests in `test-merge.js`.

**Comment by jcubic** [comment]
That's odd.

**Comment by jcubic** [comment]
Ok looks good. One more thing can you document the feature of mergeConflict Error? I hope that the website can be built, we have this legacy Azure Pipeline that gives a lot of issues.

**Comment by DanilKazanov** [comment]
I aldready tried change docs: https://github.com/isomorphic-git/isomorphic-git.github.io/pull/94, but it looks like website isn't being updated. 
About the MergeConflictError, I should write docs here https://isomorphic-git.org/docs/en/merge#manually-resolving-merge-conflicts?

**Comment by jcubic** [comment]
I've sent a message to the original author on LinkedIN, I hope he will reply there. Last time I sent him DM on twitter he didn't replied, and it seems that website is the only one thing that we don't have access to. And we don't know how to build the website.

**Comment by billiegoose** [comment]
Hiya @jcubic - sorry I don't have a Twitter (er, I mean X) account anymore. I'll add you on LinkedIn

The docs are in the main repo (this one) in the `website` folder. The build process is [here](https://github.com/isomorphic-git/isomorphic-git/blob/90ea0e34f6bb0956858213281fafff0fd8e94309/package-scripts.cjs#L79-L86) The Azure pipeline that publishes to npm also updates the main website. The `nps website.publish` script runs `./scripts/deploy-gh-pages.cjs` which (in a rather meta fashion) uses isomorphic-git to push the subdirectory with the built website to the GitHub Pages repo.

To test the docs locally, you also run `nps website` (it uses the presences of the `CI` environment variable to either run the docusaurus dev server or build and push).

**Comment by jcubic** [comment]
@billiegoose so normal release do the the update of website? We thought that the website was on [isomorphic-git.github.io](https://github.com/isomorphic-git/isomorphic-git.github.io) repo. What is this repo for then?

**Comment by billiegoose** [comment]
> @billiegoose so normal release do the the update of website? 

Yup.

> We thought that the website was on [isomorphic-git.github.io](https://github.com/isomorphic-git/isomorphic-git.github.io) repo. What is this repo for then?

Free hosting from GitHub Pages. It's not meant to be edited by humans, it's just a destination. See all the commits on the main branch?

https://github.com/isomorphic-git/isomorphic-git.github.io/commits/main

They're all made by `isomorphic-git-bot`. The commit messages match the commit messages from the main branch of this repo.

I guess the "Edit" links docusaurus makes are a little awkward since they point to that repo instead of the `website` folder of this repo.

**Comment by billiegoose** [comment]
@jcubic https://github.com/isomorphic-git/isomorphic-git/pull/1840

**Pull request merged**
