### PR TITLE
resolves #899 do not overwrite existing .git/config on init

### LINKED ISSUE #899: isogit init in existing repo overwrites .git/config unconditionally
git init documentation and behavior indicate that git init in an existing repository do not remove information from .git/config.  isomorphic-git init unconditionally overwrites .git/config.

I'd suggest that checking for the existence of .git/config and not changing it if present would be more appropriate behavior.

### PR DESCRIPTION
**Pull request by djencks**
resolves #899 
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README

running this made no changes, I got:

$ npm run add-contributor

> isomorphic-git@0.0.0-development add-contributor /Users/david/projects/isomorphic-git/isomorphic-git
> nps contributors.add

nps is executing `contributors.add` : all-contributors add
 is/are invalid contribution type(s)
The script called "contributors.add" which runs "all-contributors add" failed with exit code 1 https://github.com/sezna/nps/blob/v5.9.8/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isomorphic-git@0.0.0-development add-contributor: `nps contributors.add`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic-git@0.0.0-development add-contributor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2019-10-19T02_31_37_634Z-debug.log

### CODE REVIEW

**Comment by karma-pr-reporter** [comment]
## Test Results for 3e84e8ede39c5a942b17142347c135c831d22972:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 297  | 1    | 0    | 3m:31s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 297  | 1    | 0    | 4m:8s  | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 297  | 1    | 0    | 1m:53s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 297  | 1    | 0    | 0m:49s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 296  | 2    | 0    | 3m:35s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 297  | 1    | 0    | 3m:30s | false       |

### Longest running tests
- 34.948 secs - fetch fetch (from Github) - _Edge_
- 19.885 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 15.604 secs - fetch shallow fetch (from Github) - _Edge_
- 14.895 secs - fetch fetch (from Github) - _Firefox_
- 14.447 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 13.201 secs - fetch shallow fetch (from Github) - _Firefox_
- 12.58 secs - fetch shallow fetch since (from Github) - _Edge_
- 12.283 secs - fetch shallow fetch relative (from Github) - _Edge_
- 11.221 secs - GitPackIndex from .pack - _Firefox_
- 10.574 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 9.841 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_

**Comment by karma-pr-reporter** [comment]
## Test Results for 8f49a393aef140fd8b6bfcb9318d10d3b658aa15:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 300  | 1    | 0    | 3m:5s  | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 300  | 1    | 0    | 4m:10s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 300  | 1    | 0    | 1m:51s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 300  | 1    | 0    | 0m:46s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 299  | 2    | 0    | 3m:41s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 300  | 1    | 0    | 3m:37s | false       |

### Longest running tests
- 33.093 secs - fetch fetch (from Github) - _Edge_
- 25.054 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 23.606 secs - fetch shallow fetch relative (from Github) - _Edge_
- 18.684 secs - fetch fetch (from Github) - _Firefox_
- 13.116 secs - fetch shallow fetch (from Github) - _Edge_
- 12.256 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 11.699 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 10.665 secs - GitPackIndex to .idx file from .pack - _Firefox_
- 10.156 secs - GitPackIndex from .pack - _Firefox_
- 9.967 secs - fetch fetch --prune-tags from git-http-mock-server - _Chrome Mobile_
- 8.873 secs - fetch shallow fetch exclude (from Github) - _Edge_

**Comment by karma-pr-reporter** [comment]
## Test Results for 5f429cc7abebf9736de2cdcadb8c7464a9fe30ba:
| Browser                                 | Pass | Skip | Fail | Time   | Disconnect? |
| --------------------------------------- | ---- | ---- | ---- | ------ | ----------- |
| Chrome Mobile 69.0.3497 (Android 7.1.1) | 300  | 1    | 0    | 3m:23s | false       |
| Edge 17.17134.0 (Windows 10 0.0.0)      | 300  | 1    | 0    | 4m:15s | false       |
| Firefox 69.0.0 (Ubuntu 0.0.0)           | 300  | 1    | 0    | 1m:42s | false       |
| HeadlessChrome 0.0.0 (Linux 0.0.0)      | 300  | 1    | 0    | 0m:43s | false       |
| Mobile Safari 11.0.0 (iOS 11.2.0)       | 299  | 2    | 0    | 6m:11s | false       |
| Safari 11.1.2 (Mac OS X 10.13.6)        | 300  | 1    | 0    | 3m:43s | false       |

### Longest running tests
- 30.931 secs - fetch fetch --prune-tags from git-http-mock-server - _Safari_
- 18.43 secs - fetch fetch (from Github) - _Firefox_
- 17.946 secs - fetch shallow fetch relative (from Github) - _Edge_
- 17.621 secs - fetch fetch (from Github) - _Edge_
- 16.995 secs - GitPackIndex to .idx file from .pack - _Edge_
- 15.517 secs - fetch shallow fetch (from Github) - _Firefox_
- 15.248 secs - GitPackIndex from .pack - _Edge_
- 10.984 secs - fetch fetch --prune-tags from git-http-mock-server - _Firefox_
- 10.628 secs - merge merge 'delete-first-half' and 'delete-second-half' (dryRun, missing author) - _Edge_
- 10.294 secs - fetch shallow fetch since (from Github) - _Edge_
- 8.55 secs - fetch shallow fetch (from Github) - _Edge_

**Comment by wmhilton** [comment]
Fantastic job adding the tests by the way! Thanks SO much and we'll _definitely_ make this the **default** behavior (only behavior maybe?) in version 1.0 this December. 👍

**Pull request merged**
