### PR TITLE
feat: add `noTrack` option to checkout

### PR DESCRIPTION
**Pull request by KwintenP**
## I'm fixing a bug or typo

- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "fix: [Description of fix]"

## I'm adding a parameter to an existing command X:

- [x] add parameter to the function in `src/api/X.js` (and `src/commands/X.js` if necessary)
- [x] document the parameter in the JSDoc comment above the function
- [x] add a test case in `__tests__/test-X.js` if possible
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [x] squash merge the PR with commit message "feat(X): Added 'bar' parameter"

## I'm adding a new command:

- [ ] add as a new file in `src/api` (and `src/commands` if necessary)
- [ ] add command to `src/index.js`
- [ ] update `__tests__/test-exports.js`
- [ ] create a test in `src/__tests__`
- [ ] document the command with a JSDoc comment
- [ ] add page to the Docs Sidebar `website/sidebars.json`
- [ ] add page to the v1 Docs Sidebar `website/versioned_sidebars/version-1.x-sidebars.json`
- [ ] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] squash merge the PR with commit message "feat: Added 'X' command"

### CODE REVIEW

**Comment by mojavelinux** [comment]
Before pushing, be sure to run `npx eslint .` so that it clears any lint errors.

**Comment by KwintenP** [comment]
I'm having issues installing and running the stack tbqh.
I'm on a MBP with the m1 chip and it seems to not work that well :). Tried running the stack in a docker container but can't seem to get it quite right either.

I'm abusing CI to test my changes, which is very slow and tedious but I'll get there.

**Comment by mojavelinux** [comment]
Here's my advice for running tests without having to use the whole stack.

```
npm ci
npx nps build.rollup build.typings
npx jest __tests__/test-checkout.js
```

That's the minimum amount to get the tests working. If you need the test git server, then you also need to run test.setup and test.teardown.

```
npm ci
npx nps build.rollup build.typings
npx nps test.setup
npx jest __tests__/test-checkout.js
npx nps test.teardown
```

I can't see how that would have any trouble running on any machine.

NOTE: You can also hack package-scripts.js to create an nps task that does those steps for you. See the definition of "test" in that file.

**Comment by KwintenP** [comment]
That worked thx :)

**Comment by jcubic** [comment]
The code looks good, I only don't like a double negative. What do you think about changing it to `tracking` that is true by default? This would get rid of a double negative.

I know that in git it's named `--no-track` but it's a command-line option without value. and In git code it's probably true when it's set, so there are no double negatives.

**Comment by KwintenP** [comment]
Updated.

**Comment by jcubic** [comment]
@KwintenP thanks for working on the fix.

**Comment by mojavelinux** [comment]
The documentation for this flag is not correct. Here's what the website says:

```
track | object | If true, will not set the remote branch tracking information. Defaults to false.
```

The type should be "Boolean" and I'm pretty sure the default is true. I submitted a PR to correct it. See https://github.com/isomorphic-git/isomorphic-git/pull/1472

**Pull request merged**
