### PR TITLE
Ability to specify extra HTTP headers for network commands (fixes #530)

### LINKED ISSUE #530: support http.extraHeader in .git/config
https://git-scm.com/docs/git-config#git-config-httpextraHeader

Requested by @juancampa [here](https://github.com/isomorphic-git/isomorphic-git/issues/500#issuecomment-429878520)

Will pair nicely with #502

### PR DESCRIPTION
**Pull request by juancampa**
## I'm adding a parameter to an existing command:

- [x] add parameter to the function in `src/commands/X.js`
- [x] add parameter to [docs](https://github.com/isomorphic-git/isomorphic-git.github.io/tree/source/docs)/X.md (see https://github.com/isomorphic-git/isomorphic-git.github.io/pull/41)
- [x] add parameter to the TypeScript library definition for X in `src/index.d.ts`
- [ ] add a test case in `__tests__/test-X.js` if possible
- [x] if this is your first time contributing, run `npm run add-contributor` and follow the prompts to add yourself to the README
- [ ] make a feature commit "feat: Added 'bar' parameter to X command"

Edit: I'm "editing" the PR because that should trigger a `pull_request.edited` webhook to our good friend @isomorphic-git-bot

### CODE REVIEW

**Comment by juancampa** [comment]
Hey, @wmhilton this is ready for a final review.

About the "feat: ..." commit. Now that Github supports squash and merge, should we use that? Or should I squash all changes on my side and post another PR?

**Comment by wmhilton** [comment]
> About the "feat: ..." commit. Now that Github supports squash and merge, should we use that?

Good point! I should delete that from the template.

**Comment by wmhilton** [comment]
Also, I don't know if you noticed but the Continuous Integration tests failed, for a fairly boring reason. https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=327&view=logs There are some extra commas. (Frankly, I like trailing commas because they reduce git diff noise, but I've just been using the defaults for `prettier` and that seems to not like trailing commas.) BUT DONT BOTHER FIXING IT. Until now, the @isomorphic-git-bot only lints and auto-fixes PRs when they are first opened. But now I'm like 50% sure I've improved the bot so it can auto-fix style issues after every PR edit _with a configurable debounce_ so it is not super annoying.

**Comment by juancampa** [comment]
I'm on it :)

**Comment by juancampa** [comment]
Tests are now passing. Not sure how to tell the CI to run again. Let's see..

CI, please run tests

**Comment by wmhilton** [comment]
why tests why. Hmm, oh, it's for the "push to Github" test, I bet it's a missing Github token. I should probably just delete that test OR hardcode the Github token into the test, since it's a narrowly defined token that only has authorization to a single test repo.

**Comment by wmhilton** [comment]
Now it's failing because it can't test all the browsers its supposed to in Sauce Labs, because more environment variables. :( hang on

**Comment by wmhilton** [comment]
Turns out there's a setting that enables secrets in forks. I'll just turn that on for now.

That's not ideal, because now some clever person simply has to open up the right PR and boom they'll steal my npm publishing key lol.

I'll look into better solutions after I get this thing merged

**Comment by wmhilton** [comment]
Didn't work for some reason. 😢 

OK, new plan. I copied your branch from your fork into a branch in this repo. Closing this PR in favor of #551

Also, you have write permissions to this repo now because why not? Also @hsablonniere you have write permissions now too.) Therefore future PRs can all live happily inside _this_ fork. Which still doesn't make a ton of sense... honestly there should just be a button "trust this PR with environment vars and rerun tests". I'll tell that idea to the Azure DevOps team.

**Comment by karma-pr-reporter** [comment]
This is a test

**Comment by karma-pr-reporter** [comment]
This is a test

**Comment by karma-pr-reporter** [comment]
This is a test

**Pull request closed without merging**
