### PR TITLE
fix: don't consider identical oids as ambiguous in expandOid (#1789)

### PR DESCRIPTION
**Pull request by willstott101**
As far as expandOid is concerned duplicate objects isn't actually ambiguous... so this seems like a sane fix.

~However IDK if the fact I have an object loose as well as in a pack file is something I should be concerned about.~

The existence of this command implies that duplicate objects are a valid (if sub-optimal) state for a git repo's blobs: https://git-scm.com/docs/git-pack-redundant

    You are better off using git gc to do so, which will put objects into a new pack, removing duplicates.

### CODE REVIEW

**Comment by jcubic** [comment]
I don't think this is the right solution you just ignore that you have invalid data and return the first OID from duplicated ones.

**Comment by willstott101** [comment]
I disagree this is invalid data. I believe it's perfectly possible to end up with loose objects that are also in packs. `writeObject` for instance just writes a loose object without holding a lock or anything afaict. This could happen alongside a git gc, or during a git push from another process etc... I don't see a way in the isomorphic api to atomically do write-if-not-exists, I am currently using:
`if (!expandOid) writeObject`

I'm also not convinced it'd be invalid for a duplicate to exist temporarily during a `git gc` from another process, for instance.

**Comment by jcubic** [comment]
Sorry but if you can't provide a use case when this is broken, this is probably a useless change that only fixes some weird state you have in your app.

**Comment by jcubic** [comment]
The release job failed. I'm not sure why not all tests passed. I've restarted the job, I hope it will pass and a release will be created.

**Pull request merged**
